# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %%% QUAC: GARDEN ASSIGNMENT %%%
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

# This script uses the outputs of STRUCTURE runs including Subset (shared between MSAT and SNP)
# Garden and Wild samples to see how well different markers/approaches do at assigning garden samples
# back to their known wild provenances. It does this for Subset MSAT, SNP De novo (R80), and SNP Reference 
# (R80, 5,000 whitelisted loci) datasets.

# The functions declared at the top of the script are used for reading in outputs from the CLUMPAK software,
# which summarizes STRUCTURE results across replicate runs, and identifies "modes" of clustering. 
# For plotting, we utilize the "Major" mode identified by CLUMPAK, although the plotting functions can 
# be altered.

# Processing note: CLUMPAK outputs locate results in folders named for each K value, with the format
# "K=2", "K=3", etc. Because the "=" is difficult to deal with in BASH (similar to "/"),
# these folders have been manually renamed "K2", "K3", etc.

library(RColorBrewer)

# %%%% FUNCTIONS %%%% ----
# Read in the file generated by CLUMPP, and add/remove sample name/population name columns as required 
read.CLUMPP <- function(clumpp.outputFile, sampleNames=NULL, popNames=NULL){
  # Read int the CLUMPP output file
  Qmat <- read.table(clumpp.outputFile, header=FALSE)
  # Remove the first 5 columns, which contain sample identifiers and other characters
  Qmat <- Qmat[,-(1:5)]
  # If sample names exist, rename rows according to sample names
  if(hasArg(sampleNames)){
    rownames(Qmat) <- sampleNames
  }
  # If a vector of population names exists, add a column to the matrix which includes population identifiers
  if(hasArg(popNames)){
    Qmat <- cbind(popNames, Qmat)
    names(Qmat[,1]) <- "populations"
  }
  return(Qmat)
}

# Plotting function for single K value
plot_singleK <- function(kList, kColors, title=NULL, popNamesPresent=FALSE, xBuffer=NULL, ...){
  # If population names are present (first column of matrix), remove these prior to plotting
  if(popNamesPresent){
    kList <- kList[,-1]
  } 
  # Plotting 
  for(i in 1:length(kList)){
    if(i==1){
      # Initial barplot
      barplot(kList[,i], xlim=c(0,(nrow(kList)+35)), ylim=c(0,1.3), horiz=F, beside=F, 
              col=kColors[i], axisnames=T, space=0.2, yaxt= "n", main=title)
      off.value <- kList[,i]
    }else{
      # Subsequent barplots with offset
      barplot(kList[,i], offset=off.value, add=T, beside=F, xlim=c(0,(nrow(kList)+20)), 
              horiz=F, col=kColors[i], yaxt= "n")
      off.value <- off.value + kList[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), 
       labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
}

# Wrapper for plot_singleK, which calls that function after building filepath and reading in CLUMPP file
Plot_K <- function(clumppPath, K, Colors, sampleNames, popNames, mainTitle, 
                   parFlag=1, majorClust=TRUE, popNamesPresent=TRUE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Direct to the appropriate K folder, based on K argument
  Kfolder <- paste0("K", as.character(K),"/")
  # Read in the Q matrices in the ClumppIndFile.output file within the specified CLUMPP directory
  Kclumpp <- read.CLUMPP(paste0(clumppPath, Kfolder, clumppFolder, "ClumppIndFile.output"), 
                         sampleNames = sampleNames, popNames = popNames)
  # Plot K value
  plot_singleK(kList = Kclumpp, kValues = K, kColors = Colors, title=mainTitle, parFlag=parFlag, popNamesPresent = TRUE)
}

# Plotting function for multiple K values
plot_multipleK <- function(kList, kValues, kColors, tickMarks, parFlag=TRUE, popNamesPresent=FALSE, titleFlag=TRUE, ...){
  # Determine the number of individuals by counting rows of the kList object
  nInds <- nrow(kList[[1]])
  # If parFlag argument is TRUE, specify graphing parameter values; otherwise, default (global) par values are utilized
  # parFlag variable allows for function to be used in different contexts (showing one marker, or all 3 markers)
  if(parFlag==TRUE){
    # Set graphing parameters to allow for multiple rows (for each K value).
    par(mfrow = c(length(kList),1), mar = c(1.2,1,1.5,0.75) + 0.1, oma = c(0.5,0,2,0), mgp = c(2,1,0))
  } 
  # Loop through list of Q matrices
  for(i in 1:length(kList)){
    # If population names are present (first column of matrix), remove these prior to plotting
    if(popNamesPresent){
      kList[[i]] <- kList[[i]][,-1]
    }
    # Update graphing parameters to allow for extra space at the bottom of the graph, for lines/popNames
    if(parFlag==TRUE){
      if(i == length(kList)){
        par(mar = c(4,1,1,0.75) + 0.1)
      }
    }
    # Main plot call, and title call
    barplot(t(kList[[i]]), beside= F, col=kColors, border = 1, space = 0.05, 
            xaxt = 'n', yaxt = 'n', cex.lab = 1.2)
    title(main = paste("K =", kValues[i], sep = ' '), line=0.2, cex.main=1.6)
    # y axis
    axis(2, at = c(0, 0.25, 0.5, 0.75, 1), cex.axis = 1, las = 2, pos = -0.02)
    # For all but the last plot call, show tick marks
    if(i != length(kList)){
      axis(1, at=tickMarks, labels = FALSE, lwd.ticks = 2, tck=-0.2)
    }
  }
}

# Wrapper for plot_multipleK, which just calls that function after reading in the CLUMPP files
Plot_AllK <- function(clumppPath, Ks, Colors, sampleNames, popNames, 
                      parFlag=TRUE, tickMarks, popNamesPresent=FALSE, majorClust=TRUE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Read in the Q matrices within the specified CLUMPP directory. Hard-coded for K values 2-7!
  K2filepath <- paste0(clumppPath, "/K2", clumppFolder, "ClumppIndFile.output")
  K2clumpp <- read.CLUMPP(K2filepath, sampleNames = sampleNames, popNames = popNames)
  
  K3filepath <- paste0(clumppPath, "/K3", clumppFolder, "ClumppIndFile.output")
  K3clumpp <- read.CLUMPP(K3filepath, sampleNames = sampleNames, popNames = popNames)
  
  K4filepath <- paste0(clumppPath, "/K4", clumppFolder, "ClumppIndFile.output")
  K4clumpp <- read.CLUMPP(K4filepath, sampleNames = sampleNames, popNames = popNames)
  
  K5filepath <- paste0(clumppPath, "/K5", clumppFolder, "ClumppIndFile.output")
  K5clumpp <- read.CLUMPP(K5filepath, sampleNames = sampleNames, popNames = popNames)
  
  K6filepath <- paste0(clumppPath, "/K6", clumppFolder, "ClumppIndFile.output")
  K6clumpp <- read.CLUMPP(K6filepath, sampleNames = sampleNames, popNames = popNames)
  
  K7filepath <- paste0(clumppPath, "/K7", clumppFolder, "ClumppIndFile.output")
  K7clumpp <- read.CLUMPP(K7filepath, sampleNames = sampleNames, popNames = popNames)
  
  # Plot specified K values
  clumppList <- list(K2clumpp, K3clumpp, K4clumpp, K5clumpp, K6clumpp, K7clumpp)
  plot_multipleK(kList = clumppList, kValues = Ks, kColors = Colors, tickMarks=tickMarks, 
                 parFlag=parFlag, popNamesPresent = TRUE)
}

# %%%% QUAC %%%%
# Colors for different clusters: combinations of RGB components in hexadecimal
QUAC.colors <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', 
                 '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF') 
# Population labels
QUAC.labelNames <- c("Magazine_W","Magazine_G","Porter_W","Porter_G", "Pryor_W","Pryor_G",
                     "Sugarloaf_W", "Sugarloaf_G", "Unknown")
# Label positions (All Ks and K=4)
QUAC.labelPositions_AllKs <- c(14, 48, 78, 103, 119, 140, 170, 183, 190)
QUAC.labelPositions_K4 <- c(15, 57, 90, 116, 136, 160, 191, 209, 216)
# Tick mark positions (All Ks and K=4)
QUAC.tickMarks_AllKs <- c(0,24.1,64.2,90.1,108,126,152.3,179.8,183)
QUAC.tickMarks_K4 <- c(0,27.8,73.2,103.2,122.7,143,174.2,205.3,209)
# Variable file path: popmap file used by Stacks, which contains sample and population names
QUAC.popMap <- 
  "/RAID1/IMLS_GCCO/Analysis/Stacks/denovo_finalAssemblies/QUAC/output/populations_R80_gardenProv/QUAC_popmap_gardenProv"
# Vectors for sample and population names (used for all MSAT and SNP datasets)
QUAC.sampleNames <- as.character(factor(read.table(QUAC.popMap, header=FALSE)[,1]))
QUAC.popNames <- as.character(factor(read.table(QUAC.popMap, header=FALSE)[,2]))

# %%% MSAT ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.MSAT.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/MSAT/QUAC/Subset_GardenAndWild_NoK/Output/CLUMPAK/Output/mainPipeline/QUAC.MSAT.Subset.GW.NoK_K2-7/"

# All Ks (K=2-7) ----
Plot_AllK(clumppPath = QUAC.MSAT.clumppDir, Ks=2:7, Colors = QUAC.colors, tickMarks = QUAC.tickMarks_AllKs,
          sampleNames = QUAC.sampleNames, popNames = QUAC.popNames)
# Plot tick marks (along bottom)
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.7)
# Add group labels
text(x=QUAC.labelPositions_AllKs, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Garden and Wild Samples (Subset), MSAT", outer=TRUE, cex=1.3)

# K=4 ----
# Altering margins
par(mar = c(5,3,2,2), oma=c(1,0,1,0), mfrow = c(1,1))
# Plot QUAC K=4 values 
Plot_K(QUAC.MSAT.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Garden and Wild Samples (Subset), MSAT: K4")
# Plot tick marks
axis(1, at=QUAC.tickMarks_K4, labels = FALSE, lwd.ticks = 2, tck=-0.08)
# Add group labels
text(x=QUAC.labelPositions_K4, y=-0.07, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# %%% SNP ----
# ---- DE NOVO ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.SNP.DN.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUAC/Subset/GardenAndWild_NoK/Output/CLUMPAK/Output/mainPipeline/QUAC.SNP.DN.Subset.GW.NoK_K2-7/"

# All Ks (K=2-7) ----
Plot_AllK(clumppPath = QUAC.SNP.DN.clumppDir, Ks=2:7, Colors = QUAC.colors, tickMarks = QUAC.tickMarks_AllKs, 
          sampleNames = QUAC.sampleNames, popNames = QUAC.popNames)
# Plot tick marks (along bottom)
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.7)
# Add group labels
text(x=QUAC.labelPositions_AllKs, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Garden and Wild Samples (Subset), SNP: De novo (R80)", outer=TRUE, cex=1.3)

# K=4 ----
# Altering margins
par(mar = c(5,3,2,2), oma=c(1,0,1,0), mfrow = c(1,1))
# Plot QUAC K=4 values 
Plot_K(QUAC.SNP.DN.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Garden and Wild Samples (Subset), SNP: De novo (R80): K4")
# Plot tick marks
axis(1, at=QUAC.tickMarks_K4, labels = FALSE, lwd.ticks = 2, tck=-0.08)
# Add group labels
text(x=QUAC.labelPositions_K4, y=-0.07, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# ---- REFERENCE ----
# For QUAC Reference analyses, Stacks populations module was run using 5,000 randomly selected "whitelisted" loci,
# in order to ease STRUCTURE computations
QUAC.SNP.REF.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/reference_filteredReads/QUAC/Subset/GardenAndWild_NoK_WL/Output/CLUMPAK/Output/mainPipeline/QUAC.Subset.GW.NoK.WL_K2-7/"

# All Ks (K=2-7) ----
Plot_AllK(clumppPath = QUAC.SNP.REF.clumppDir, Ks=2:7, Colors = QUAC.colors, tickMarks = QUAC.tickMarks_AllKs,
          sampleNames = QUAC.sampleNames, popNames = QUAC.popNames)
# Plot tick marks (along bottom)
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.7)
# Add group labels
text(x=QUAC.labelPositions_AllKs, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Garden and Wild Samples (Subset), SNP: Reference (R80)", outer=TRUE, cex=1.3)

# K=4 ----
# Altering margins
par(mar = c(5,3,2,2), oma=c(1,0,1,0), mfrow = c(1,1))
# Plot QUAC K=4 values 
Plot_K(QUAC.SNP.REF.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Garden and Wild Samples (Subset), SNP: Reference (R80): K4")
# Plot tick marks
axis(1, at=QUAC.tickMarks_K4, labels = FALSE, lwd.ticks = 2, tck=-0.08)
# Add group labels
text(x=QUAC.labelPositions_K4, y=-0.07, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# ---- PLOTTING MULTIPLE DATASETS ----
# All Ks, MajorCluster results ----
# Graphing parameters for all 6 K values (2-7) and all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
layout(mat = matrix(1:18, nrow = 6, ncol = 3))
par(mar = c(1.2,1,1.2,0.75) + 0.1, oma = c(0.5,1,4,0), mgp = c(2,1,0))
# MSAT
Plot_AllK(clumppPath = QUAC.MSAT.clumppDir, Ks=2:7, Colors = QUAC.colors, tickMarks = QUAC.tickMarks_AllKs, 
          popNames = QUAC.popNames, parFlag = FALSE)
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
mtext("QUAC: MSAT (Subset)", side=3, line=40.5, cex=0.8)
# SNP: DE NOVO 
Plot_AllK(clumppPath = QUAC.SNP.DN.clumppDir, Ks=2:7, Colors = QUAC.colors, tickMarks = QUAC.tickMarks_AllKs, 
          popNames = QUAC.popNames, parFlag = FALSE)
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
mtext("QUAC: SNP, De novo (Subset, R80)", side=3, line=40.5, cex=0.8)
# SNP: REFERENCE
Plot_AllK(clumppPath = QUAC.SNP.REF.clumppDir, Ks=2:7, Colors = QUAC.colors, tickMarks = QUAC.tickMarks_AllKs,
          popNames = QUAC.popNames, parFlag = FALSE)
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
mtext("QUAC: SNP, Reference (Subset, R80)", side=3, line=40.5, cex=0.8)

# Geographic K (K=4), MajorCluster results ----
# Graphing parameters for K=4 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
par(mfrow=c(3,1), mar = c(4.5,3,1.2,3), oma=c(1,0,1,0))
# MSAT
Plot_K(QUAC.MSAT.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
      mainTitle = "QUAC MSAT  (Subset): K4")
axis(1, at=QUAC.tickMarks_K4, labels = FALSE, lwd.ticks = 2, tck=-0.1)
text(x=QUAC.labelPositions_K4, y=-0.07, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)
# SNP: DE NOVO 
Plot_K(QUAC.SNP.DN.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC SNP (Subset), De novo (R80): K4")
axis(1, at=QUAC.tickMarks_K4, labels = FALSE, lwd.ticks = 2, tck=-0.1)
text(x=QUAC.labelPositions_K4, y=-0.07, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)
# SNP: REFERENCE
Plot_K(QUAC.SNP.REF.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC SNP (Subset), Reference (R80): K4")
axis(1, at=QUAC.tickMarks_K4, labels = FALSE, lwd.ticks = 2, tck=-0.1)
text(x=QUAC.labelPositions_K4, y=-0.07, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# Geographic K (K=4), Summary results (averaged across major and minor clusters) ----
# Graphing parameters for K=4 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
par(mfrow=c(3,1), mar = c(4.5,3,1.2,3), oma=c(1,0,1,0))
# MSAT
Plot_K(QUAC.MSAT.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC MSAT (Subset, Summary): K4", majorClust = FALSE)
axis(1, at=QUAC.tickMarks_K4, labels = FALSE, lwd.ticks = 2, tck=-0.1)
text(x=QUAC.labelPositions_K4, y=-0.07, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)
# SNP: DE NOVO 
Plot_K(QUAC.SNP.DN.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC SNP (Subset, Summary), De novo (R80): K4", majorClust = FALSE)
axis(1, at=QUAC.tickMarks_K4, labels = FALSE, lwd.ticks = 2, tck=-0.1)
text(x=QUAC.labelPositions_K4, y=-0.07, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)
# SNP: REFERENCE
Plot_K(QUAC.SNP.REF.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC SNP (Subset, Summary), Reference (R80): K4", majorClust = FALSE)
axis(1, at=QUAC.tickMarks_K4, labels = FALSE, lwd.ticks = 2, tck=-0.1)
text(x=QUAC.labelPositions_K4, y=-0.07, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)
