# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# %%% QUBO STRUCTURE ASSIGNMENTS PLOTTED SPATIALLY %%%
# %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

# This is an exploratory script which plots QUBO samples as points according to 
# their collection sites (latitude=X; longitude=Y). Points are colored according to STRUCTURE
# assignments at K=2.

library(ggplot2)
library(scatterpie)
library(scales)

# %%%% FUNCTIONS %%%% ----
# Read in the file generated by CLUMPP, and add/remove sample name/population name columns as required 
read.CLUMPP <- function(clumpp.outputFile, sampleNames=NULL, popNames=NULL){
  # browser()
  # Read int the CLUMPP output file
  Qmat <- read.table(clumpp.outputFile, header=FALSE)
  # Remove the first 5 columns, which contain sample identifiers and other characters
  Qmat <- Qmat[,-(1:5)]
  # If sample names exist, rename rows according to sample names
  if(hasArg(sampleNames)){
    rownames(Qmat) <- sampleNames
  }
  # If a vector of population names exists, add a column to the matrix which includes population identifiers
  if(hasArg(popNames)){
    Qmat <- cbind(popNames, Qmat)
    names(Qmat[,1]) <- "populations"
  }
  return(Qmat)
}

# %%% MSAT %%% ----
# %%% SNP: DE NOVO %%% ----
# Specify the location of the CLUMPP files, which contains the Q matrix assigning individuals to clusters
QUBO.SNP.DN.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUBO/Subset/Wild_Ordered2/output/CLUMPAK/Output/mainPipeline/QUBO_SNP_DN_mainPipeline/K2/MajorCluster/CLUMPP.files/ClumppIndFile.output"
# Obtain sample and population names from popmap file (associated with genind file)
# Declare filepath to relevant output folder from Stacks
genpop.filePath <- 
  "/RAID1/IMLS_GCCO/Analysis/Stacks/denovo_finalAssemblies/QUBO/output/populations_wild_R0_NOMAF_1SNP_Subset_Ordered2//"
# Create a vector of sample names
QUBO.sampleNames <- 
  factor(read.table(paste0(genpop.filePath,"QUBO_popmap_wild_Subset_Ordered2"), header=FALSE)[,1])
# Create a vector of population names
QUBO.popNames <- 
  factor(read.table(paste0(genpop.filePath,"QUBO_popmap_wild_Subset_Ordered2"), header=FALSE)[,2])
# Build matrix of Q values, with sample and population names
QUBO.Qmat <- read.CLUMPP(QUBO.SNP.DN.clumppDir, sampleNames = QUBO.sampleNames, popNames = QUBO.popNames)

# READ IN WILD SAMPLE LOCATION VALUES
# Filepath for csv, which contains lat/long values for Subset SNP samples.
# Sample order matches that of Q matrix (samples grouped by population). Columns 4 and 5 contain relevant values
QUBO.sampleLocations.filepath <- 
  "/home/akoontz/Documents/SSRvSNP/Code/popAnalyses/STRUCTURE/QUBO.SNP.Wild.Subset_sampleLocations.csv"
QUBO.sampleLocations <- read.csv2(QUBO.sampleLocations.filepath,sep=",")[,4:5]
# Combine lat/long values with Q.mat
QUBO.Qmat <- as.data.frame(cbind(QUBO.sampleLocations,QUBO.Qmat))

# SCATTERPIE ----
# REFORMAT Q MATRIX
# Include all Q matrix values in a single column (for plotting in scatterpie)
values <- c(QUBO.Qmat[,4],QUBO.Qmat[,5])
# Create "groups" variable (for plotting in scatterpie)
groups <- c(rep("A",nrow(QUBO.Qmat)),rep("B",nrow(QUBO.Qmat)))
# Rearrange matrix to contain multiple iterations of lat/longs (for plotting in scatterpie)
QUBO.Qmat.sp <- rbind(QUBO.Qmat,QUBO.Qmat)
QUBO.Qmat.sp <- cbind(QUBO.Qmat.sp,groups,values)[,-(4:5)]
colnames(QUBO.Qmat.sp) <- c("lat","long","popNames", "groups", "values")

# PLOT SCATTERPLOTS ACCORDING TO LAT/LONG VALUES USING SCATTERPIE
ggplot() + geom_scatterpie(aes(x=long, y=lat, group=popNames), data=QUBO.Qmat.sp,
                           cols=c("A","B")) + coord_equal()
# Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : non-numeric argument to binary operator
ggplot() + geom_scatterpie(aes(x=long, y=lat), data=QUBO.Qmat.sp, cols=c("A", "B")) + coord_fixed()
# Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : non-numeric argument to binary operator

# Scatterpie demonstration
d <- data.frame(x=rnorm(5), y=rnorm(5))
d$A <- abs(rnorm(5, sd=1))
d$B <- abs(rnorm(5, sd=2))
d$C <- abs(rnorm(5, sd=3))
ggplot() + geom_scatterpie(aes(x=x, y=y), data=d, cols=c("A", "B", "C")) + coord_fixed()
d <- tidyr::gather(d, key="letters", value="value", -x:-y)
ggplot() + geom_scatterpie(aes(x=x, y=y), data=d, cols="letters", long_format=TRUE) + coord_fixed()

# COLOR GRADIENT ----
# Generate a color palette, from red to blue
drgPal <- colorRampPalette(c("darkred","grey"))
# Assign colors for each Q matrix value, by referring to items within the color palette
clusterColors <- drgPal(1000)[as.numeric(cut(QUBO.Qmat$V6,breaks = 1000))]
# Give the points transparency
clusterColors <- alpha(clusterColors, alpha=0.6)
# Append colors to the sample matrix
QUBO.Qmat.cg <- cbind(QUBO.Qmat, clusterColors)

# Generate a plot of points
plot(QUBO.Qmat.cg$Longitude, QUBO.Qmat.cg$Latitude, col=QUBO.Qmat.cg$clusterColors, pch=16, cex=2.1,
     xlab="Longitude", ylab="Latitude", main="QUBO sample locations (De novo, R80)")
# Add legend
legend(x=-86.2, y=33.6,legend=c("Cluster 1", "Cluster 2"), col=c("darkred","grey"), pch = c(20,20), cex=1.5)

# Zoom in on bottom left portion of above plot
plot(QUBO.Qmat.cg$Longitude, QUBO.Qmat.cg$Latitude, col=QUBO.Qmat.cg$clusterColors, pch=16, cex=1.5,
     xlab="Longitude", ylab="Latitude", main="Southwest Cluster", xlim=c(-86.855,-86.655), ylim=c(33.295,33.57))
# Zoom in on central portion of above plot
plot(QUBO.Qmat.cg$Longitude, QUBO.Qmat.cg$Latitude, col=QUBO.Qmat.cg$clusterColors, pch=16, cex=1.5,
     xlab="Longitude", ylab="Latitude", main="Central Range", xlim=c(-86.4,-86.275), ylim=c(33.6,33.96))
# Zoom in on upper right portion of above plot
plot(QUBO.Qmat.cg$Longitude, QUBO.Qmat.cg$Latitude, col=QUBO.Qmat.cg$clusterColors, pch=16, cex=1.5,
     xlab="Longitude", ylab="Latitude", main="Northeast Cluster", xlim=c(-86.034,-86.026), ylim=c(34.046,34.05))
