# %%%%%%%%%%%%%%%%%%%%%%
# %%% PLOT STRUCTURE %%%
# %%%%%%%%%%%%%%%%%%%%%%

# This script declares functions for taking the the summarized Q matrix values 
# from a CLUMPP run and building a corresponding STRUCTURE plot. Specifically, 
# in terms of the outputs from CLUMPAK, for a given K value, it reads
# in the CLUMPP output file ("CLUMPP.files/ClumppIndFile.output") 
# and will plot those values.

# Using several different wrapper functions, the script will analyze Q matrices create STRUCTURE plots.
# It does this for both QUAC and QUBO, analyzing Subset Wild samples (that is, wild individuals that are
# analyzed in both MSAT and SNP studies, for each species)

# Processing note: CLUMPAK outputs locate results in folders named for each K value, with the format
# "K=2", "K=3", etc. Because the "=" is difficult to deal with in BASH (similar to "/"),
# these folders have been manually renamed "K2", "K3", etc.

library(RColorBrewer)

# %%%% FUNCTIONS %%%% ----
# Read in the file generated by CLUMPP, and add/remove sample name/population name columns as required 
read.CLUMPP <- function(clumpp.outputFile, sampleNames=NULL, popNames=NULL){
  # Read int the CLUMPP output file
  Qmat <- read.table(clumpp.outputFile, header=FALSE)
  # Remove the first 5 columns, which contain sample identifiers and other characters
  Qmat <- Qmat[,-(1:5)]
  # If sample names exist, rename rows according to sample names
  if(hasArg(sampleNames)){
    rownames(Qmat) <- sampleNames
  }
  # If a vector of population names exists, add a column to the matrix which includes population identifiers
  if(hasArg(popNames)){
    Qmat <- cbind(popNames, Qmat)
    names(Qmat[,1]) <- "populations"
  }
  return(Qmat)
}

# Plotting function for single K value
plot_singleK <- function(kList, kColors, title=NULL, popNamesPresent=FALSE, ...){
  # If population names are present (first column of matrix), remove these prior to plotting
  if(popNamesPresent){
    kList <- kList[,-1]
  } 
  # Plotting 
  for(i in 1:length(kList)){
    if(i==1){
      # Initial barplot
      barplot(kList[,i], xlim=c(0,(nrow(kList)+20)), ylim=c(0,1.3), horiz=F, beside=F, 
              col=kColors[i], axisnames=T, space=0.2, yaxt= "n", main=title)
      off.value <- kList[,i]
    }else{
      # Subsequent barplots with offset
      barplot(kList[,i], offset=off.value, add=T, beside=F, xlim=c(0,(nrow(kList)+20)), 
              horiz=F, col=kColors[i], yaxt= "n")
      off.value <- off.value + kList[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), 
       labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
}

# Wrapper for plot_singleK, which calls that function after building filepath and reading in CLUMPP file
Plot_K <- function(clumppPath, K, Colors, sampleNames, popNames, mainTitle=NULL, 
                   parFlag=1, majorClust=TRUE, popNamesPresent=TRUE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Direct to the appropriate K folder, based on K argument
  Kfolder <- paste0("K", as.character(K),"/")
  # Read in the Q matrices in the ClumppIndFile.output file within the specified CLUMPP directory
  Kclumpp <- read.CLUMPP(paste0(clumppPath, Kfolder, clumppFolder, "ClumppIndFile.output"), 
                         sampleNames = sampleNames, popNames = popNames)
  # Plot K value
  plot_singleK(kList = Kclumpp, kValues = K, kColors = Colors, title=mainTitle, parFlag=parFlag, popNamesPresent = TRUE)
}

# Plotting function for multiple K values
plot_multipleK <- function(kList, kValues, kColors, tickMarks, parFlag=TRUE, popNamesPresent=FALSE, titleFlag=TRUE, ...){
  # Determine the number of individuals by counting rows of the kList object
  nInds <- nrow(kList[[1]])
  # If parFlag argument is TRUE, specify graphing parameter values; otherwise, default (global) par values are utilized
  # parFlag variable allows for function to be used in different contexts (showing one marker, or all 3 markers)
  if(parFlag==TRUE){
    # Set graphing parameters to allow for multiple rows (for each K value).
    par(mfrow = c(length(kList),1), mar = c(1.2,1,1.5,0.75) + 0.1, oma = c(0.5,0,2,0), mgp = c(2,1,0))
  } 
  # Loop through list of Q matrices
  for(i in 1:length(kList)){
    # If population names are present (first column of matrix), remove these prior to plotting
    if(popNamesPresent){
      kList[[i]] <- kList[[i]][,-1]
    }
    # Update graphing parameters to allow for extra space at the bottom of the graph, for lines/popNames
    if(parFlag==TRUE){
      if(i == length(kList)){
        par(mar = c(4,1,1,0.75) + 0.1)
      }
    }
    # Main plot call, and title call
    barplot(t(kList[[i]]), beside= F, col=kColors, border = 1, space = 0.05, 
            xaxt = 'n', yaxt = 'n', cex.lab = 1.2)
    title(main = paste("K =", kValues[i], sep = ' '), line=0.2, cex.main=1.6)
    # y axis
    axis(2, at = c(0, 0.25, 0.5, 0.75, 1), cex.axis = 1, las = 2, pos = -0.02)
    # For all but the last plot call, show tick marks
    if(i != length(kList)){
      axis(1, at=tickMarks, labels = FALSE, lwd.ticks = 2, tck=-0.15)
    }
  }
}

# Wrapper for plot_multipleK, which just calls that function after reading in the CLUMPP files
Plot_AllK <- function(clumppPath, Ks, Colors, sampleNames, popNames, 
                      parFlag=TRUE, tickMarks, popNamesPresent=FALSE, majorClust=TRUE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Read in the Q matrices within the specified CLUMPP directory. Hard-coded for K values 2-7!
  K2filepath <- paste0(clumppPath, "/K2", clumppFolder, "ClumppIndFile.output")
  K2clumpp <- read.CLUMPP(K2filepath, sampleNames = sampleNames, popNames = popNames)
  
  K3filepath <- paste0(clumppPath, "/K3", clumppFolder, "ClumppIndFile.output")
  K3clumpp <- read.CLUMPP(K3filepath, sampleNames = sampleNames, popNames = popNames)
  
  K4filepath <- paste0(clumppPath, "/K4", clumppFolder, "ClumppIndFile.output")
  K4clumpp <- read.CLUMPP(K4filepath, sampleNames = sampleNames, popNames = popNames)
  
  K5filepath <- paste0(clumppPath, "/K5", clumppFolder, "ClumppIndFile.output")
  K5clumpp <- read.CLUMPP(K5filepath, sampleNames = sampleNames, popNames = popNames)
  
  K6filepath <- paste0(clumppPath, "/K6", clumppFolder, "ClumppIndFile.output")
  K6clumpp <- read.CLUMPP(K6filepath, sampleNames = sampleNames, popNames = popNames)
  
  K7filepath <- paste0(clumppPath, "/K7", clumppFolder, "ClumppIndFile.output")
  K7clumpp <- read.CLUMPP(K7filepath, sampleNames = sampleNames, popNames = popNames)
  
  # Plot specified K values
  clumppList <- list(K2clumpp, K3clumpp, K4clumpp, K5clumpp, K6clumpp, K7clumpp)
  plot_multipleK(kList = clumppList, kValues = Ks, kColors = Colors, tickMarks=tickMarks, 
                 parFlag=parFlag, popNamesPresent = TRUE)
}

# %%%% QUAC %%%% ----
# Colors for different clusters: combinations of RGB components in hexadecimal
QUAC.colors <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', 
                 '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF') 
# Population labels
QUAC.labelNames <- c("Porter", "Magazine", "Pryor", "Sugarloaf")

# Variable file path: popmap file used by Stacks, which contains sample and population names
QUAC.popMap <- 
  "/RAID1/IMLS_GCCO/Analysis/Stacks/denovo_finalAssemblies/QUAC/output/populations_wild_R80_NOMAF_1SNP_NoK/QUAC_popmap_wild_NoK"
# Vectors for sample and population names (used for all MSAT and SNP datasets)
QUAC.sampleNames <- as.character(factor(read.table(QUAC.popMap, header=FALSE)[,1]))
QUAC.popNames <- as.character(factor(read.table(QUAC.popMap, header=FALSE)[,2]))
# Label positions (All Ks and K=4)
QUAC.labelPositions_AllKs <- c(13.2, 33.2, 54.1, 83)
QUAC.labelPositions_SingleK <- c(15, 43.8, 67.9, 95)
# Tick mark positions (All Ks and K=4)
QUAC.tickMarks_AllKs <- c(26.3, 38, 68.2)
QUAC.tickMarks_SingleK <- c(0,30,57.6,78.1)

# %%% MSAT ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.MSAT.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/MSAT/QUAC/Subset_Wild_NoK/output/CLUMPAK/Output/mainPipeline/QUAC.MSAT.Subset.Wild.NoK_K2-7/"

# All Ks (QUAC wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUAC.MSAT.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          popNames = QUAC.popNames, tickMarks = QUAC.tickMarks_AllKs)
# Plot tick marks (along bottom)
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
# Add group labels
text(x=QUAC.labelPositions_AllKs, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Wild Samples (Subset), MSAT", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))
# Plot QUAC K=5 values (Evanno Best K)
Plot_K(QUAC.MSAT.clumppDir, K=5, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), MSAT: K5 (Evanno)")
# Plot tick marks
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
# Add group labels
text(x=QUAC.labelPositions_SingleK, y=-0.075, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# Plot QUAC K=5 values (Max Probability Best K)
Plot_K(QUAC.MSAT.clumppDir, K=5, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), MSAT: K5 (Max Probability)")
# Plot tick marks
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
# Add group labels
text(x=QUAC.labelPositions_SingleK, y=-0.075, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# %%% SNP ----
# ---- DE NOVO ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.SNP.DN.S.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUAC/Subset/Wild_NoK/output/CLUMPAK/Output/mainPipeline/QUAC.DNFA.Subset.Wild.NoK_K2-7/"
# All Ks (QUAC wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUAC.SNP.DN.S.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          sampleNames = QUAC.sampleNames, popNames = QUAC.popNames, tickMarks = QUAC.tickMarks_AllKs)
# Plot tick marks (along bottom)
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
# Add group labels
text(x=QUAC.labelPositions_AllKs, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Wild Samples (Subset), SNP: De novo", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))

# Plot QUAC K=5 values (Evanno Best K)
Plot_K(QUAC.SNP.DN.S.clumppDir, K=5, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), SNP: De novo: K5 (Evanno)")
# Plot tick marks
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
# Add group labels
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# Plot QUAC K=4 values (Max Probability Best K)
Plot_K(QUAC.SNP.DN.S.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), SNP: De novo: K4 (Max Probability)")
# Plot tick marks
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
# Add group labels
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# ---- REFERENCE ----
# For QUAC Reference analyses, the original dataset was too large (~15,000 loci) to process 
# using CLUMPAKs Best K pipeline. Therefore, and randomly selected subset of 5,000 loci were 
# used for the STRUCTURE and CLUMPAK steps. These are shown here.
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.SNP.REF.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/reference_filteredReads/QUAC/Subset/Wild_NoK_WL/output/CLUMPAK/Output/mainPipeline/QUAC.Subset.Wild.NoK.WL_K2-7/"
# All Ks (QUAC wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUAC.SNP.REF.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          sampleNames = QUAC.sampleNames, popNames = QUAC.popNames, tickMarks = QUAC.tickMarks_AllKs)
# Plot tick marks (along bottom)
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
# Add group labels
text(x=QUAC.labelPositions_AllKs, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Wild Samples (Subset), SNP: Reference", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))

# Plot QUAC K=3 values (Evanno Best K)
Plot_K(QUAC.SNP.REF.clumppDir, K=3, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames,
       mainTitle = "QUAC Wild Samples (Subset), SNP: Reference K3 (Evanno)")
# Plot tick marks
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
# Add group labels
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# Plot QUAC K=4 values (Max Probability Best K)
Plot_K(QUAC.SNP.REF.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames,
       mainTitle = "QUAC Wild Samples (Subset), SNP: Reference: K4 (Max Probability)")
# Plot tick marks
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
# Add group labels
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# ---- PLOTTING MULTIPLE DATASETS ----
# All Ks, MajorCluster results ----
# Graphing parameters for all 6 K values (2-7) and all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
layout(mat = matrix(1:18, nrow = 6, ncol = 3))
par(mar = c(1.2,1,1.2,0.75) + 0.1, oma = c(0.5,1,4,0), mgp = c(2,1,0))
# MSAT
Plot_AllK(clumppPath = QUAC.MSAT.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          tickMarks = QUAC.tickMarks_AllKs, popNames = QUAC.popNames, parFlag = FALSE)
# Plot tick marks (along bottom) and title
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
mtext("QUAC: MSAT (Subset)", side=3, line=52.5, cex=0.8)
# SNP: DE NOVO 
Plot_AllK(clumppPath = QUAC.SNP.DN.S.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          tickMarks = QUAC.tickMarks_AllKs, popNames = QUAC.popNames, parFlag = FALSE)
# Plot tick marks (along bottom) and title
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
mtext("QUAC: SNP, De novo (Subset, R80)", side=3, line=52.5, cex=0.8)
# SNP: REFERENCE
Plot_AllK(clumppPath = QUAC.SNP.REF.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          tickMarks = QUAC.tickMarks_AllKs, popNames = QUAC.popNames, parFlag = FALSE)
# Plot tick marks (along bottom) and title
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
mtext("QUAC: SNP, Reference (Subset, R80)", side=3, line=52.5, cex=0.8)

# All Ks, Summary results (averaged across major and minor clusters) ----
# Graphing parameters for all 6 K values (2-7) and all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
layout(mat = matrix(1:18, nrow = 6, ncol = 3))
par(mar = c(1.2,1,1.2,0.75) + 0.1, oma = c(0.5,1,4,0), mgp = c(2,1,0))
# MSAT
Plot_AllK(clumppPath = QUAC.MSAT.clumppDir, Ks=2:7, Colors = QUAC.colors, popNames = QUAC.popNames, 
          tickMarks = QUAC.tickMarks_AllKs, parFlag = FALSE, majorClust = FALSE)
# Plot tick marks (along bottom) and title
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
mtext("QUAC: MSAT (Subset, Summary)", side=3, line=52.5, cex=0.8)
# SNP: DE NOVO 
Plot_AllK(clumppPath = QUAC.SNP.DN.S.clumppDir, Ks=2:7, Colors = QUAC.colors, popNames = QUAC.popNames, 
          tickMarks = QUAC.tickMarks_AllKs, parFlag = FALSE, majorClust = FALSE)
# Plot tick marks (along bottom) and title
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
mtext("QUAC: SNP, De novo (Subset, Summary, R80)", side=3, line=52.5, cex=0.8)
# SNP: REFERENCE
Plot_AllK(clumppPath = QUAC.SNP.REF.clumppDir, Ks=2:7, Colors = QUAC.colors, popNames = QUAC.popNames, 
          tickMarks = QUAC.tickMarks_AllKs, parFlag = FALSE, majorClust = FALSE)
# Plot tick marks (along bottom) and title
axis(1, at=QUAC.tickMarks_AllKs, labels = FALSE, lwd.ticks = 2, tck=-0.2)
mtext("QUAC: SNP, Reference (Subset, Summary, R80)", side=3, line=52.5, cex=0.8)

# Geographic K (K=4), MajorCluster results ----
# Graphing parameters for K=4 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
par(mfrow=c(3,1), mar = c(4.5,3,1.2,3), oma=c(1,0,1,0))
# MSAT
Plot_K(QUAC.MSAT.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames)
# Plot title, tick marks, and group labels
title(main="QUAC MSAT: K4", line=-2)
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.3)
# SNP: DE NOVO 
Plot_K(QUAC.SNP.DN.S.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames)
# Plot title, tick marks, and group labels
title(main="QUAC SNP, De novo (R80): K4", line=-2)
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.3)
# SNP: REFERENCE
Plot_K(QUAC.SNP.REF.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames)
# Plot title, tick marks, and group labels
title(main="QUAC SNP, Reference (R80): K4", line=-2)
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.3)

# Geographic K (K=4), Summary results (averaged across major and minor clusters) ----
# Graphing parameters for K=4 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
# par(mfrow=c(3,1), mar = c(4.5,3,1.2,3), oma=c(1,0,1,0))
par(mfrow=c(3,1), mar = c(4.5,3,0.9,3), oma=c(1,0,0.8,0))
# MSAT
Plot_K(QUAC.MSAT.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, majorClust = FALSE)
# Plot title, tick marks, and group labels
title(main="QUAC MSAT (Subset, Summary): K4", line=-2)
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.3)
# SNP: DE NOVO 
Plot_K(QUAC.SNP.DN.S.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, majorClust = FALSE)
# Plot title, tick marks, and group labels
title(main="QUAC SNP, De novo (Subset, Summary, R80): K4", line=-2)
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.3)
# SNP: REFERENCE
Plot_K(QUAC.SNP.REF.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, majorClust = FALSE)
# Plot title, tick marks, and group labels
title(main="QUAC SNP, Reference (Subset, Summary, R80): K4", line=-2)
axis(1, at=QUAC.tickMarks_SingleK, labels = FALSE, lwd.ticks = 2, tck=-0.15)
text(x=QUAC.labelPositions_SingleK, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.3)

# %%%% QUBO %%%% ----
# Colors for different clusters: combinations of RGB components in hexadecimal
QUBO.colors <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', 
                 '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF')
# Population labels
QUBO.labelNames <- c("Oakbrook", "Worldsong", "Wattsville", "MossRock", "Irondale",
                     "OakMountainSP", "HindsRoad", "Peavine", "Pop11")
# Variable file path: popmap file used by Stacks (Subset, so same samples as seen within MSAT dataset)
QUBO.popMap <- 
  "/RAID1/IMLS_GCCO/Analysis/Stacks/denovo_finalAssemblies/QUBO/output/populations_wild_R80_NOMAF_1SNP_Subset_Ordered2/QUBO_popmap_wild_Subset_Ordered2"
# Vectors for sample and population names (used for all MSAT and SNP datasets)
QUBO.sampleNames <- factor(read.table(QUBO.popMap, header=FALSE)[,1])
QUBO.popNames <- factor(read.table(QUBO.popMap, header=FALSE)[,2])
# Label positions (All Ks and K=4)
QUBO.labelPositions_AllKs <- c(13.2, 33.2, 54.1, 83)
QUBO.labelPositions_SingleK <- c(15, 43.8, 67.9, 95)
# Tick mark positions (All Ks and K=4)
QUBO.tickMarks_AllKs <- c(26.3, 38, 68.2)
QUBO.tickMarks_SingleK <- c(0,30,57.6,78.1)

# %%% MSAT ----
# Variable file path: directory containing all CLUMPPs output to read in
QUBO.MSAT.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/MSAT/QUBO/Subset_Wild_Ordered2/output/CLUMPAK/Output/mainPipeline/QUBO.MSAT.W.Subset.Ordered2_K2-7/"

# All Ks (QUBO wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUBO.MSAT.clumppDir, Ks=2:7, Colors = QUBO.colors, popNames = QUBO.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUBO.labelPositions <- c(1, 6, 14.8, 24.2, 31, 49.0, 75.8, 90.4, 96.2)
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,9.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(10.0,19.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(20.4,27.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(28.7,33.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(34.1,63.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(64.7,86.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(87.6,93.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(93.9,98.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)

# lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.11, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.0)
# Title
mtext(text = "QUBO Wild Samples (Subset), MSAT", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.8,3,4,3), oma=c(1,0,1,0), mgp=c(1,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6.6, 17.4, 28, 36.4, 58.4, 90.7, 103.9, 111.7) 

# Plot QUBO K=4 values (Evanno Best K)
Plot_K(QUBO.MSAT.clumppDir, K=4, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), MSAT: K4 (Evanno)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,22.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(23.4,31.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(32.9,40.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.3,75.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(76.4,100.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(101.5,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# Plot QUBO K=2 values (Max Probability Best K)
Plot_K(QUBO.MSAT.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), MSAT: K2 (Max Probability)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,22.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(23.4,31.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(32.9,40.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.3,75.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(76.4,100.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(101.5,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# %%% SNP ----
# ---- DE NOVO ----
# Variable file path: directory containing all CLUMPPs output to read in
QUBO.SNP.DN.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUBO/Subset/Wild_Ordered2/output/CLUMPAK/Output/mainPipeline/QUBO_SNP_DN_mainPipeline/"

# All Ks (QUBO wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUBO.SNP.DN.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          sampleNames = QUBO.sampleNames, popNames = QUBO.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUBO.labelPositions <- c(1, 6, 14.8, 24.2, 31, 49.0, 75.8, 90.4, 96.2)
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,9.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(10.0,19.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(20.4,27.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(28.7,33.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(34.1,63.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(64.7,86.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(87.6,93.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(93.9,98.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.13, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.0)
# Title
mtext(text = "QUBO Wild Samples (Subset), SNP: De novo", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.8,3,4,3), oma=c(1,0,1,0), mgp=c(1,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6.6, 17.4, 28, 36.4, 58.4, 90.7, 103.9, 111.7) 

# Plot QUBO K=3 values (Evanno Best K)
Plot_K(QUBO.SNP.DN.clumppDir, K=3, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), SNP: De novo: K3 (Evanno)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,22.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(23.4,31.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(32.9,40.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.3,75.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(76.4,100.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(101.5,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# Plot QUBO K=2 values (Max Probability Best K)
Plot_K(QUBO.SNP.DN.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), SNP: De novo: K2 (Max Probability)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,22.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(23.4,31.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(32.9,40.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.3,75.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(76.4,100.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(101.5,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# ---- REFERENCE ----
# Variable file path: directory containing all CLUMPPs output to read in
QUBO.SNP.REF.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUBO/Subset/Wild_Ordered2/output/CLUMPAK/Output/mainPipeline/QUBO_SNP_DN_mainPipeline/"

# All Ks (QUBO wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUBO.SNP.REF.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          sampleNames = QUBO.sampleNames, popNames = QUBO.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUBO.labelPositions <- c(1, 6, 14.8, 24.2, 31, 49.0, 75.8, 90.4, 96.2)
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,9.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(10.0,19.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(20.4,27.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(28.7,33.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(34.1,63.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(64.7,86.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(87.6,93.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(93.9,98.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.13, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.0)
# Title
mtext(text = "QUBO Wild Samples (Subset), SNP: Reference", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.8,3,4,3), oma=c(1,0,1,0), mgp=c(1,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6.6, 17.4, 28, 36.4, 58.4, 90.7, 103.9, 111.7)

# Plot QUBO K=4 values (Evanno Best K)
Plot_K(QUBO.SNP.REF.clumppDir, K=4, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), SNP: Reference: K4 (Evanno)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,22.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(23.4,31.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(32.9,40.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.3,75.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(76.4,100.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(101.5,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# Plot QUBO K=2 values (Max Probability Best K)
Plot_K(QUBO.SNP.REF.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), SNP: Reference: K2 (Max Probability)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,22.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(23.4,31.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(32.9,40.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.3,75.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(76.4,100.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(101.5,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# ---- PLOTTING MULTIPLE DATASETS ----
# All Ks, MajorCluster results ----
# Graphing parameters for all 6 K values (2-7) and all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
layout(mat = matrix(1:18, nrow = 6, ncol = 3))
par(mar = c(1.2,1,1,0.75) + 0.1, oma = c(0.5,1,4,0), mgp = c(2,1,0))
# MSAT
Plot_AllK(clumppPath = QUBO.MSAT.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          popNames = QUBO.popNames, parFlag = FALSE)
mtext("QUBO: MSAT (Subset)", side=3, line=65, cex=0.8)
# SNP: DE NOVO 
Plot_AllK(clumppPath = QUBO.SNP.DN.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          popNames = QUBO.popNames, parFlag = FALSE)
mtext("QUBO: SNP, De novo (Subset, R80)", side=3, line=65, cex=0.8)
# SNP: REFERENCE
Plot_AllK(clumppPath = QUBO.SNP.REF.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          popNames = QUBO.popNames, parFlag = FALSE)
mtext("QUBO: SNP, Reference (Subset, R80)", side=3, line=65, cex=0.8)

# All Ks, Summary results ----
# Graphing parameters for all 6 K values (2-7) and all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
layout(mat = matrix(1:18, nrow = 6, ncol = 3))
par(mar = c(1.2,1,1,0.75) + 0.1, oma = c(0.5,1,4,0), mgp = c(2,1,0))
# MSAT
Plot_AllK(clumppPath = QUBO.MSAT.clumppDir, Ks=2:7, Colors = QUBO.colors, popNames = QUBO.popNames, 
          parFlag = FALSE, majorClust = FALSE)
mtext("QUBO: MSAT (Subset, Summary)", side=3, line=65, cex=0.8)
# SNP: DE NOVO 
Plot_AllK(clumppPath = QUBO.SNP.DN.clumppDir, Ks=2:7, Colors = QUBO.colors, popNames = QUBO.popNames, 
          parFlag = FALSE, majorClust = FALSE)
mtext("QUBO: SNP, De novo (Subset, Summary, R80)", side=3, line=65, cex=0.8)
# SNP: REFERENCE
Plot_AllK(clumppPath = QUBO.SNP.REF.clumppDir, Ks=2:7, Colors = QUBO.colors, popNames = QUBO.popNames, 
          parFlag = FALSE, majorClust = FALSE)
mtext("QUBO: SNP, Reference (Subset, Summary, R80)", side=3, line=65, cex=0.8)

# Geographic K (K=2), MajorCluster results ----
# Graphing parameters for K=2 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
par(mfrow=c(3,1), mar = c(4.8,3,1,3), oma=c(1,0,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6, 16.4, 28.0, 34.9, 58.5, 90.0, 104.4, 111.2)
# MSAT
Plot_K(QUBO.MSAT.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO MSAT: K2")
# SNP: DE NOVO 
Plot_K(QUBO.SNP.DN.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO SNP, De novo (R80): K2")
# SNP: REFERENCE
Plot_K(QUBO.SNP.REF.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO SNP, Reference (R80): K2")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,22.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(23.4,31.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(32.9,40.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.3,75.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(76.4,100.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(101.5,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.055, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.15)

# Geographic K (K=2), Summary results ----
# Graphing parameters for K=2 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
par(mfrow=c(3,1), mar = c(4.8,3,1,3), oma=c(1,0,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6, 16.4, 28.0, 34.9, 58.5, 90.0, 104.4, 111.2)
# MSAT
Plot_K(QUBO.MSAT.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO MSAT (Subset, Summary): K2", majorClust = FALSE)
# SNP: DE NOVO 
Plot_K(QUBO.SNP.DN.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO SNP, De novo (Subset, Summary, R80): K2", majorClust = FALSE)
# SNP: REFERENCE
Plot_K(QUBO.SNP.REF.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO SNP, Reference (Subset, Summary, R80): K2", majorClust = FALSE)
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,22.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(23.4,31.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(32.9,40.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.3,75.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(76.4,100.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(101.5,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.055, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.15)
