# %%%%%%%%%%%%%%%%%%%%%%
# %%% PLOT STRUCTURE %%%
# %%%%%%%%%%%%%%%%%%%%%%

# This script declares functions for taking the the summarized Q matrix values 
# from a CLUMPP run and building a corresponding STRUCTURE plot. Specifically, 
# in terms of the outputs from CLUMPAK, for a given K value, it reads
# in the CLUMPP output file ("CLUMPP.files/ClumppIndFile.output") 
# and will plot those values.

# Using several different wrapper functions, the script will analyze Q matrices create STRUCTURE plots.
# It does this for both QUAC and QUBO, analyzing Subset Wild samples (that is, wild individuals that are
# analyzed in both MSAT and SNP studies, for each species)

library(RColorBrewer)

# %%%% FUNCTIONS %%%% ----
# Read in the file generated by CLUMPP, and add/remove sample name/population name columns as required 
read.CLUMPP <- function(clumpp.outputFile, sampleNames=NULL, popNames=NULL){
  # Read int the CLUMPP output file
  Qmat <- read.table(clumpp.outputFile, header=FALSE)
  # Remove the first 5 columns, which contain sample identifiers and other characters
  Qmat <- Qmat[,-(1:5)]
  # If sample names exist, rename rows according to sample names
  if(hasArg(sampleNames)){
    rownames(Qmat) <- sampleNames
  }
  # If a vector of population names exists, add a column to the matrix which includes population identifiers
  if(hasArg(popNames)){
    Qmat <- cbind(popNames, Qmat)
    names(Qmat[,1]) <- "populations"
  }
  return(Qmat)
}

# Plotting function for single K value
plot_singleK <- function(kList, kColors, title=NULL, popNamesPresent=FALSE, ...){
  # If population names are present (first column of matrix), remove these prior to plotting
  if(popNamesPresent){
    kList <- kList[,-1]
  } 
  # Plotting 
  for(i in 1:length(kList)){
    if(i==1){
      # Initial barplot
      barplot(kList[,i], xlim=c(0,(nrow(kList)+20)), ylim=c(0,1.3), horiz=F, beside=F, 
              col=kColors[i], axisnames=T, space=0.2, yaxt= "n", main=title)
      off.value <- kList[,i]
    }else{
      # Subsequent barplots with offset
      barplot(kList[,i], offset=off.value, add=T, beside=F, xlim=c(0,(nrow(kList)+20)), 
              horiz=F, col=kColors[i], yaxt= "n")
      off.value <- off.value + kList[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), 
       labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
}

# Wrapper for plot_singleK, which calls that function after building filepath and reading in CLUMPP file
Plot_K <- function(clumppPath, K, Colors, sampleNames, popNames, mainTitle, 
                   parFlag=1, majorClust=FALSE, popNamesPresent=TRUE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Direct to the appropriate K folder, based on K argument
  Kfolder <- paste0("K", as.character(K),"/")
  # Read in the Q matrices in the ClumppIndFile.output file within the specified CLUMPP directory
  Kclumpp <- read.CLUMPP(paste0(clumppPath, Kfolder, clumppFolder, "ClumppIndFile.output"), 
                         sampleNames = sampleNames, popNames = popNames)
  # Plot K value
  plot_singleK(kList = Kclumpp, kValues = K, kColors = Colors, title=mainTitle, parFlag=parFlag, popNamesPresent = TRUE)
}

# Plotting function for multiple K values
plot_multipleK <- function(kList, kValues, kColors, parFlag=TRUE, popNamesPresent=FALSE, titleFlag=TRUE, ...){
  # Determine the number of individuals by counting rows of the kList object
  nInds <- nrow(kList[[1]])
  # If parFlag argument is 1, specify graphing parameter values; otherwise, default (global) par values are utilized
  # parFlag variable allows for function to be used in different contexts (showing one marker, or all 3 markers)
  if(parFlag==TRUE){
    # Set graphing parameters to allow for multiple rows (for each K value).
    par(mfrow = c(length(kList),1), mar = c(1.2,1,1.5,0.75) + 0.1, oma = c(0.5,0,2,0), mgp = c(2,1,0))
  } 
  # Loop through list of Q matrices
  for(i in 1:length(kList)){
    # If population names are present (first column of matrix), remove these prior to plotting
    if(popNamesPresent){
      kList[[i]] <- kList[[i]][,-1]
    }
    # Update graphing parameters to allow for extra space at the bottom of the graph, for lines/popNames
    if(parFlag==1){
      if(i == length(kList)){
        par(mar = c(4,1,1,0.75) + 0.1)
      }
    }
    # Main plot call, and title call
    barplot(t(kList[[i]]), beside= F, col=kColors, border = 1, space = 0.05, 
            xaxt = 'n', yaxt = 'n', cex.lab = 1.2)
    title(main = paste("K =", kValues[i], sep = ' '), line=0.2, cex.main=1.6)
    # y axis
    axis(2, at = c(0, 0.25, 0.5, 0.75, 1), cex.axis = 1, las = 2, pos = -0.02)
  }
}

# Wrapper for plot_multipleK, which just calls that function after reading in the CLUMPP files
Plot_AllK <- function(clumppPath, Ks, Colors, sampleNames, popNames, 
                      parFlag=1, popNamesPresent=FALSE, majorClust=FALSE, ...){
  # Direct to either the MajorCluster folder of the general CLUMPP.files folder, depending on majorClust flag
  if(majorClust==TRUE){
    clumppFolder <- "/MajorCluster/CLUMPP.files/"
  } else{
    clumppFolder <- "/CLUMPP.files/"
  }
  # Read in the Q matrices within the specified CLUMPP directory. Hard-coded for K values 2-7!
  K2filepath <- paste0(clumppPath, "/K2", clumppFolder, "ClumppIndFile.output")
  K2clumpp <- read.CLUMPP(K2filepath, sampleNames = sampleNames, popNames = popNames)
  
  K3filepath <- paste0(clumppPath, "/K3", clumppFolder, "ClumppIndFile.output")
  K3clumpp <- read.CLUMPP(K3filepath, sampleNames = sampleNames, popNames = popNames)
  
  K4filepath <- paste0(clumppPath, "/K4", clumppFolder, "ClumppIndFile.output")
  K4clumpp <- read.CLUMPP(K4filepath, sampleNames = sampleNames, popNames = popNames)
  
  K5filepath <- paste0(clumppPath, "/K5", clumppFolder, "ClumppIndFile.output")
  K5clumpp <- read.CLUMPP(K5filepath, sampleNames = sampleNames, popNames = popNames)
  
  K6filepath <- paste0(clumppPath, "/K6", clumppFolder, "ClumppIndFile.output")
  K6clumpp <- read.CLUMPP(K6filepath, sampleNames = sampleNames, popNames = popNames)
  
  K7filepath <- paste0(clumppPath, "/K7", clumppFolder, "ClumppIndFile.output")
  K7clumpp <- read.CLUMPP(K7filepath, sampleNames = sampleNames, popNames = popNames)
  
  # Plot specified K values
  clumppList <- list(K2clumpp, K3clumpp, K4clumpp, K5clumpp, K6clumpp, K7clumpp)
  plot_multipleK(kList = clumppList, kValues = Ks, kColors = Colors, parFlag=parFlag, popNamesPresent = TRUE)
}

# %%%% QUAC %%%% ----
# Colors for different clusters: combinations of RGB components in hexadecimal
QUAC.colors <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', 
                 '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF') 
# Population labels
QUAC.labelNames <- c("Porter", "Magazine", "Pryor", "Sugarloaf", "Kessler")

# Variable file path: popmap file used by Stacks, which contains sample and population names
QUAC.popMap <- 
  "/RAID1/IMLS_GCCO/Analysis/Stacks/denovo_finalAssemblies/QUAC/output/populations_wild_R80_NOMAF_1SNP/QUAC_popmap_wild"
# Vectors for sample and population names (used for all MSAT and SNP datasets)
QUAC.sampleNames <- factor(read.table(QUAC.popMap, header=FALSE)[,1])
QUAC.popNames <- factor(read.table(QUAC.popMap, header=FALSE)[,2])

# %%% MSAT ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.MSAT.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/MSAT/QUAC/Subset_Wild/output/CLUMPAK/Output/mainPipeline/QUAC.MSAT.Subset.Wild_K2-7/"

# All Ks (QUAC wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUAC.MSAT.clumppDir, Ks=2:7, Colors = QUAC.colors, popNames = QUAC.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUAC.labelPositions <- c(13, 38, 59, 79, 100) 
# Plot lines
lines(x = c(0.2,26), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(26.7,50.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(50.7,68), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(68.7,95.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(96.3,101.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Wild Samples (Subset), MSAT", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUAC.labelPositions <- c(15, 44, 68, 93.5, 112) 
# Plot QUAC K=5 values (Evanno Best K)
Plot_K(QUAC.MSAT.clumppDir, K=5, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), MSAT: K5 (Evanno)")
# Plot lines
lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# Plot QUAC K=6 values (Max Probability Best K)
Plot_K(QUAC.MSAT.clumppDir, K=6, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), MSAT: K6 (Max Probability)")
# Plot lines
lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# %%% SNP ----
# ---- DE NOVO, SUBSET ADEGENET ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.SNP.DN.A.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUAC/Subset/Wild/subsetAdegenet/output/CLUMPAK/Output/mainPipeline/QUAC.DNFA.Subset.Wild.Adegenet_K2-7/"

# All Ks (QUAC wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUAC.SNP.DN.A.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          sampleNames = QUAC.sampleNames, popNames = QUAC.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUAC.labelPositions <- c(13, 38, 59, 79, 100) 
# Plot lines
lines(x = c(0.2,26), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(26.7,50.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(50.7,68), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(68.7,95.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(96.3,101.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Wild Samples (Subset), SNP: De novo, Adegenet", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUAC.labelPositions <- c(15, 44, 68, 93.5, 112)

# Plot QUAC K=5 values (Evanno Best K)
Plot_K(QUAC.SNP.DN.A.clumppDir, K=5, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), SNP: De novo, Adegenet: K5 (Evanno)")
# Plot lines
lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# Plot QUAC K=7 values (Max Probability Best K)
Plot_K(QUAC.SNP.DN.A.clumppDir, K=7, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), SNP: De novo, Adegenet: K7 (Max Probability)")
# Plot lines
lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# ---- DE NOVO, SUBSET STACKS ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.SNP.DN.S.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUAC/Subset/Wild/subsetStacks/output/CLUMPAK/Output/mainPipeline/QUAC.DNFA.Subset.Wild.Stacks_K2-7/"

# All Ks (QUAC wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUAC.SNP.DN.S.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          sampleNames = QUAC.sampleNames, popNames = QUAC.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUAC.labelPositions <- c(13, 38, 59, 79, 100) 
# Plot lines
lines(x = c(0.2,26), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(26.7,50.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(50.7,68), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(68.7,95.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(96.3,101.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Wild Samples (Subset), SNP: De novo, Stacks", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUAC.labelPositions <- c(15, 44, 68, 93.5, 112) 

# Plot QUAC K=6 values (Evanno Best K)
Plot_K(QUAC.SNP.DN.S.clumppDir, K=6, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), SNP: De novo, Stacks: K6 (Evanno)")
# Plot lines
lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# Plot QUAC K=4 values (Max Probability Best K)
Plot_K(QUAC.SNP.DN.S.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC Wild Samples (Subset), SNP: De novo, Stacks: K4 (Max Probability)")
# Plot lines
lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# ---- REFERENCE ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.SNP.REF.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/reference_filteredReads/QUAC/Subset/Wild/output/CLUMPAK/Output/mainPipeline/QUAC.REF.Subset.Wild_K2-7/"

# All Ks (QUAC wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUAC.SNP.REF.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          sampleNames = QUAC.sampleNames, popNames = QUAC.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUAC.labelPositions <- c(13, 38, 59, 79, 100) 
# Plot lines
lines(x = c(0.2,26), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(26.7,50.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(50.7,68), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(68.7,95.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(96.3,101.9), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.2, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.2)
# Title
mtext(text = "QUAC Wild Samples (Subset), SNP: Reference", outer=TRUE, cex=1.3)

# Best K ----
# Currently, we don't know optimal K values for QUAC Reference dataset
# # Plot two charts per window (one for each Best K metric)
# par(mfrow=c(2,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))
# # Plot QUAC K=6 values (Evanno Best K)
# QUAC.SNP.REF.clumppDir <- 
#   "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUAC/Subset/Wild/subsetStacks/output/CLUMPAK/Output/mainPipeline/QUAC.DNFA.Subset.Wild.Stacks/K6/"
# Plot_K(QUAC.SNP.REF.clumppDir, K=6, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
#        mainTitle = "QUAC Wild Samples (Subset), SNP: Reference K6 (Evanno)")
# # Variables for lines designating groups beneath K charts. 
# lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
# QUAC.labelPositions <- c(15, 44, 68, 93.5, 112) 
# # Plot lines
# lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# # Add group labels
# text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)
# 
# # Plot QUAC K=4 values (Max Probability Best K)
# QUAC.SNP.REF.clumppDir <- 
#   "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUAC/Subset/Wild/subsetStacks/output/CLUMPAK/Output/mainPipeline/QUAC.DNFA.Subset.Wild.Stacks/K4/"
# Plot_K(QUAC.SNP.REF.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
#        mainTitle = "QUAC Wild Samples (Subset), SNP: Reference: K4 (Max Probability)")
# # Plot lines
# lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# # Add group labels
# text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1)

# ---- PLOTTING MULTIPLE DATASETS ----
# All Ks ----
# Graphing parameters for all 6 K values (2-7) and all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
layout(mat = matrix(1:18, nrow = 6, ncol = 3))
par(mar = c(1.2,1,1,0.75) + 0.1, oma = c(0.5,1,4,0), mgp = c(2,1,0))
# MSAT
Plot_AllK(clumppPath = QUAC.MSAT.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          popNames = QUAC.popNames, parFlag = FALSE)
mtext("QUAC: MSAT (Subset)", side=3, line=39, cex=0.8)
# SNP: DE NOVO (STACKS)
Plot_AllK(clumppPath = QUAC.SNP.DN.S.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          popNames = QUAC.popNames, parFlag = FALSE)
mtext("QUAC: SNP, De novo (Subset, R80)", side=3, line=39, cex=0.8)
# SNP: REFERENCE
Plot_AllK(clumppPath = QUAC.SNP.REF.clumppDir, Ks=2:7, Colors = QUAC.colors, 
          popNames = QUAC.popNames, parFlag = FALSE)
mtext("QUAC: SNP, Reference (Subset, R80)", side=3, line=39, cex=0.8)

# All Ks, MajorCluster results ----
# Graphing parameters for all 6 K values (2-7) and all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
layout(mat = matrix(1:18, nrow = 6, ncol = 3))
par(mar = c(1.2,1,1,0.75) + 0.1, oma = c(0.5,1,4,0), mgp = c(2,1,0))
# MSAT
Plot_AllK(clumppPath = QUAC.MSAT.clumppDir, Ks=2:7, Colors = QUAC.colors, popNames = QUAC.popNames, 
          parFlag = FALSE, majorClust = TRUE)
mtext("QUAC: MSAT (Subset, MajorCluster)", side=3, line=39, cex=0.8)
# SNP: DE NOVO (STACKS)
Plot_AllK(clumppPath = QUAC.SNP.DN.S.clumppDir, Ks=2:7, Colors = QUAC.colors, popNames = QUAC.popNames, 
          parFlag = FALSE, majorClust = TRUE)
mtext("QUAC: SNP, De novo (Subset, MajorCluster, R80)", side=3, line=39, cex=0.8)
# SNP: REFERENCE
Plot_AllK(clumppPath = QUAC.SNP.REF.clumppDir, Ks=2:7, Colors = QUAC.colors, popNames = QUAC.popNames, 
          parFlag = FALSE, majorClust = TRUE)
mtext("QUAC: SNP, Reference (Subset, MajorCluster, R80)", side=3, line=39, cex=0.8)

# Geographic K (K=4) ----
# Graphing parameters for K=4 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
par(mfrow=c(3,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUAC.labelPositions <- c(15, 44, 68, 93.5, 112) 
# MSAT
Plot_K(QUAC.MSAT.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
      mainTitle = "QUAC MSAT: K4")
# SNP: DE NOVO (STACKS)
Plot_K(QUAC.SNP.DN.S.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC SNP, De novo (R80): K4")
# SNP: REFERENCE
Plot_K(QUAC.SNP.REF.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC SNP, Reference (R80): K4")
# Plot lines
lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.3)

# Geographic K (K=4), MajorCluster results ----
# Graphing parameters for K=4 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
par(mfrow=c(3,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUAC.labelPositions <- c(15, 44, 68, 93.5, 112)
# MSAT
Plot_K(QUAC.MSAT.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC MSAT: K4", majorClust = TRUE)
# SNP: DE NOVO (STACKS)
Plot_K(QUAC.SNP.DN.S.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC SNP, De novo (R80): K4", majorClust = TRUE)
# SNP: REFERENCE
Plot_K(QUAC.SNP.REF.clumppDir, K=4, Colors = QUAC.colors, QUAC.sampleNames, QUAC.popNames, 
       mainTitle = "QUAC SNP, Reference (R80): K4", majorClust = TRUE)
# Plot lines
lines(x = c(0.2,29.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(30.5,57.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.5,77.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(78.8,108.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(109.7,116.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUAC.labelPositions, y=-0.063, srt=35, adj=1, xpd=TRUE, labels=QUAC.labelNames, cex=1.3)

# %%%% QUBO %%%% ----
# Colors for different clusters: combinations of RGB components in hexadecimal
QUBO.colors <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', 
                 '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF')
# Population labels
QUBO.labelNames <- c("Oakbrook", "Worldsong", "Irondale", "BTKC", "EBSCO_Parking", "Peavine",
                     "Wattsville", "MossRock", "EBSCO_Ridge","HindsRoad", "Pop11")
# Variable file path: popmap file used by Stacks (Subset, so same samples as seen within MSAT dataset)
QUBO.popMap <- 
  "/RAID1/IMLS_GCCO/Analysis/Stacks/denovo_finalAssemblies/QUBO/output/populations_wild_R80_NOMAF_1SNP_Subset/QUBO_popmap_wild_Subset"
# Vectors for sample and population names (used for all MSAT and SNP datasets)
QUBO.sampleNames <- factor(read.table(QUBO.popMap, header=FALSE)[,1])
QUBO.popNames <- factor(read.table(QUBO.popMap, header=FALSE)[,2])

# %%% MSAT ----
# Variable file path: directory containing all CLUMPPs output to read in
QUBO.MSAT.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/MSAT/QUBO/Subset_Wild/output/CLUMPAK/Output/mainPipeline/QUBO_MSAT_Subset_Wild_K2-7/"

# All Ks (QUBO wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUBO.MSAT.clumppDir, Ks=2:7, Colors = QUBO.colors, popNames = QUBO.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUBO.labelPositions <- c(1, 5.8, 13.2, 20.9, 29.9, 38.0, 45.8, 54.5, 65.2, 82.6, 96.2) 
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.3,9.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(9.7,16.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(17.0,24.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(25.3,34.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(34.9,41.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.4,50.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(50.5,58.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(59.1,71.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(71.8,93.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(93.9,98.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.13, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.0)
# Title
mtext(text = "QUBO Wild Samples (Subset), MSAT", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.5,3,4,3), oma=c(1,0,1,0), mgp=c(1,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6.6, 15, 24, 34.4, 43.5, 52.4, 62.4, 74.6, 94.3, 110.3) 

# Plot QUBO K=6 values (Evanno Best K)
Plot_K(QUBO.MSAT.clumppDir, K=6, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), MSAT: K6 (Evanno)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,18.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(19.7,28.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(29.4,39.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(40.2,46.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(47.5,57.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.0,66.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(67.8,81.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(82.2,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# Plot QUBO K=2 values (Max Probability Best K)
Plot_K(QUBO.MSAT.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), MSAT: K2 (Max Probability)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,18.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(19.7,28.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(29.4,39.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(40.2,46.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(47.5,57.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.0,66.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(67.8,81.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(82.2,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# %%% SNP ----
# ---- DE NOVO ----
# Variable file path: directory containing all CLUMPPs output to read in
QUBO.SNP.DN.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUBO/Subset/Wild/output/CLUMPAK/Output/mainPipeline/QUBO.DNFA.R80.NOMAF.1SNP.Wild_K2-7/"

# All Ks (QUBO wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUBO.SNP.DN.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          sampleNames = QUBO.sampleNames, popNames = QUBO.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUBO.labelPositions <- c(1, 5.8, 13.2, 20.9, 29.9, 38.0, 45.8, 54.5, 65.2, 82.6, 96.2) 
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.3,9.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(9.7,16.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(17.0,24.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(25.3,34.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(34.9,41.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.4,50.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(50.5,58.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(59.1,71.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(71.8,93.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(93.9,98.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.13, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.0)
# Title
mtext(text = "QUBO Wild Samples (Subset), SNP: De novo", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.5,3,4,3), oma=c(1,0,1,0), mgp=c(1,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6.6, 15, 24, 34.4, 43.5, 52.4, 62.4, 74.6, 94.3, 110.3)

# Plot QUBO K=3 values (Evanno Best K)
Plot_K(QUBO.SNP.DN.clumppDir, K=3, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), SNP: De novo, Adegenet: K3 (Evanno)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,18.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(19.7,28.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(29.4,39.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(40.2,46.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(47.5,57.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.0,66.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(67.8,81.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(82.2,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# Plot QUBO K=2 values (Max Probability Best K)
Plot_K(QUBO.SNP.DN.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), SNP: De novo, Adegenet: K2 (Max Probability)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,18.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(19.7,28.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(29.4,39.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(40.2,46.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(47.5,57.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.0,66.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(67.8,81.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(82.2,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# ---- REFERENCE ----
# Variable file path: directory containing all CLUMPPs output to read in
QUBO.SNP.REF.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/STRUCTURE/denovo_finalAssemblies/QUBO/Subset/Wild/output/CLUMPAK/Output/mainPipeline/QUBO.DNFA.R80.NOMAF.1SNP.Wild_K2-7/"

# All Ks (QUBO wild samples, K=2-7) ----
Plot_AllK(clumppPath = QUBO.SNP.REF.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          sampleNames = QUBO.sampleNames, popNames = QUBO.popNames)
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.05,2)
QUBO.labelPositions <- c(1, 5.8, 13.2, 20.9, 29.9, 38.0, 45.8, 54.5, 65.2, 82.6, 96.2) 
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.3,9.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(9.7,16.6), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(17.0,24.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(25.3,34.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(34.9,41.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(41.4,50.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(50.5,58.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(59.1,71.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(71.8,93.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(93.9,98.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.13, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.0)
# Title
mtext(text = "QUBO Wild Samples (Subset), SNP: Reference", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4.5,3,4,3), oma=c(1,0,1,0), mgp=c(1,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6.6, 15, 24, 34.4, 43.5, 52.4, 62.4, 74.6, 94.3, 110.3) 

# Plot QUBO K=4 values (Evanno Best K)
Plot_K(QUBO.SNP.REF.clumppDir, K=4, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), SNP: De novo, Adegenet: K4 (Evanno)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,18.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(19.7,28.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(29.4,39.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(40.2,46.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(47.5,57.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.0,66.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(67.8,81.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(82.2,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# Plot QUBO K=2 values (Max Probability Best K)
Plot_K(QUBO.SNP.REF.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO Wild Samples (Subset), SNP: De novo, Adegenet: K2 (Max Probability)")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,18.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(19.7,28.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(29.4,39.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(40.2,46.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(47.5,57.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.0,66.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(67.8,81.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(82.2,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1)

# ---- PLOTTING MULTIPLE DATASETS ----
# All Ks ----
# Graphing parameters for all 6 K values (2-7) and all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
layout(mat = matrix(1:18, nrow = 6, ncol = 3))
par(mar = c(1.2,1,1,0.75) + 0.1, oma = c(0.5,1,4,0), mgp = c(2,1,0))
# MSAT
Plot_AllK(clumppPath = QUBO.MSAT.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          popNames = QUBO.popNames, parFlag = FALSE)
mtext("QUBO: MSAT (Subset)", side=3, line=39, cex=0.8)
# SNP: DE NOVO (STACKS)
Plot_AllK(clumppPath = QUBO.SNP.DN.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          popNames = QUBO.popNames, parFlag = FALSE)
mtext("QUBO: SNP, De novo (Subset, R80)", side=3, line=39, cex=0.8)
# SNP: REFERENCE
Plot_AllK(clumppPath = QUBO.SNP.REF.clumppDir, Ks=2:7, Colors = QUBO.colors, 
          popNames = QUBO.popNames, parFlag = FALSE)
mtext("QUBO: SNP, Reference (Subset, R80)", side=3, line=39, cex=0.8)

# All Ks, MajorCluster results ----
# Graphing parameters for all 6 K values (2-7) and all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
layout(mat = matrix(1:18, nrow = 6, ncol = 3))
par(mar = c(1.2,1,1,0.75) + 0.1, oma = c(0.5,1,4,0), mgp = c(2,1,0))
# MSAT
Plot_AllK(clumppPath = QUBO.MSAT.clumppDir, Ks=2:7, Colors = QUBO.colors, popNames = QUBO.popNames, 
          parFlag = FALSE, majorClust = TRUE)
mtext("QUBO: MSAT (Subset, MajorCluster)", side=3, line=39, cex=0.8)
# SNP: DE NOVO (STACKS)
Plot_AllK(clumppPath = QUBO.SNP.DN.clumppDir, Ks=2:7, Colors = QUBO.colors, popNames = QUBO.popNames, 
          parFlag = FALSE, majorClust = TRUE)
mtext("QUBO: SNP, De novo (Subset, MajorCluster, R80)", side=3, line=39, cex=0.8)
# SNP: REFERENCE
Plot_AllK(clumppPath = QUBO.SNP.REF.clumppDir, Ks=2:7, Colors = QUBO.colors, popNames = QUBO.popNames, 
          parFlag = FALSE, majorClust = TRUE)
mtext("QUBO: SNP, Reference (Subset, MajorCluster, R80)", side=3, line=39, cex=0.8)

# Geographic K (K=6) ----
# Graphing parameters for K=6 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
par(mfrow=c(3,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6.6, 15, 24, 34.4, 43.5, 52.4, 62.4, 74.6, 94.3, 110.3) 
# MSAT
Plot_K(QUBO.MSAT.clumppDir, K=6, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO MSAT: K6")
# SNP: DE NOVO (STACKS)
Plot_K(QUBO.SNP.DN.clumppDir, K=6, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO SNP, De novo (R80): K6")
# SNP: REFERENCE
Plot_K(QUBO.SNP.REF.clumppDir, K=6, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO SNP, Reference (R80): K6")
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,18.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(19.7,28.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(29.4,39.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(40.2,46.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(47.5,57.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.0,66.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(67.8,81.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(82.2,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.3)

# Geographic K (K=2), MajorCluster results ----
# Graphing parameters for K=4 across all 3 datasets (MSAT, SNP: De novo, SNP: Reference)
par(mfrow=c(3,1), mar = c(4.5,3,1,3), oma=c(1,0,1,0))
# Variables for lines designating groups beneath K charts. 
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
QUBO.labelPositions <- c(1, 6.6, 15, 24, 34.4, 43.5, 52.4, 62.4, 74.6, 94.3, 110.3) 
# MSAT
Plot_K(QUBO.MSAT.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO MSAT: K2", majorClust = TRUE)
# SNP: DE NOVO (STACKS)
Plot_K(QUBO.SNP.DN.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO SNP, De novo (R80): K2", majorClust = TRUE)
# SNP: REFERENCE
Plot_K(QUBO.SNP.REF.clumppDir, K=2, Colors = QUBO.colors, QUBO.sampleNames, QUBO.popNames, 
       mainTitle = "QUBO SNP, Reference (R80): K2", majorClust = TRUE)
# Plot lines
lines(x = c(0,2.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(2.7,10.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(11.2,18.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(19.7,28.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(29.4,39.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(40.2,46.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(47.5,57.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(58.0,66.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(67.8,81.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(82.2,106.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(107.4,113.2), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=QUBO.labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=QUBO.labelNames, cex=1.2)
