#!/bin/bash

# This script contains various commands used for cleaning the raw NextRAD data used for the IMLS_GCCO SSRvSNP analysis.
# Commands are divided into sections based on their purpose

#----------------------------------------------------
# %%%%% PULLING IN DATA, CREATING SAMPLE SHEET %%%%%
#----------------------------------------------------
# Pull data from SNPsaurus sharesite (411 GB)
wget -r -nH --cut-dirs=1 --no-parent --reject "index.html*" https://gc3fstorage.uoregon.edu/HG3YYDSX2/GC3F-PE-4637/

# Random stuff: extracting parts of the file names to create a sample sheet (use sed and awk for text matching)
ls | cut -f1 -d"_" >> prelim_Barcodes.text
sed -n '1~2!p' prelim_Barcodes.txt >> Barcodes.txt
ls | awk -F'_' '{print $2}' >> prelim_SampleNames.txt
sed -n '1~2!p' prelim_SampleNames.txt >> SampleNames.txt

#------------------------------------------------------------
# %%%%% SETTING MAXIMUM FILE LIMITS FOR PROCESS_RADTAGS %%%%%
#------------------------------------------------------------
# For NextRAD data, there are 382 pairs of sequences. Each of these pairs will generate 4 files in Stacks (Read 1, Read 2, rem 1, rem 2)
# Accessing that many files in a Linux system at once surpasses maximum open file limit, triggering an obscure error (From Stacks: "Error opening output file")
# Need to increase maximum allowable number of open files. Steps numbered below

# 1. First, check the limits on the number of open files
# "Hard" open file limit
ulimit -Hn
# "Soft" open file limit
ulimit -Sn

# 2. Two files need to be changed. Make copies of each file before altering originals (i.e. sudo cp originalFile backupFile)
# A. Access the /etc/security/limits.conf file, and add the relevant line

# sudo nano /etc/security/limits.conf
# Add below line to increase soft file limit
# user		soft	nofile	4096

# (Where 4096 is the amount you want to be allowable; increase to a maximum of the hard limit)
# (Tip: Lines in this file are of the format below)
#<domain/user>		<type>	<item>	<value>

# B. Access the /etc/pam.d/common-session file, then add the relevant line

#sudo nano /etc/pam.d/common-session
# Add below line
#session required pan_limits.so

# 3. Reboot computer

# 4. Recall ulimit commands to check limits successfully changed
ulimit -Hn
ulimit -Sn

#-------------------------------------
# %%%%% STACKS: PROCESS RADTAGS %%%%%
#-------------------------------------
# Data is already demultiplexed. The process_radtags command is used to rename files, clean up messy sequences, and merge pair ends
# The files generated by the process_radtags command are passed onto either the de novo assembly (denovo_map.pl) or reference mapping command (ref_map.pl)
# -b specifies barcodes file (for renaming samples to original names);
# --c cleans the data, removing any read with an uncalled base;
# --q performs quality filtering: within a moving window (of length 0.15*total read length), if average score is Phred 10 or less, read is discarded;
# --paired indicates paired end reads;
# --index-index indicates that barcodes are in the headers of the FASTQ files (for forward and reverse reads)

# Preliminary runs showed the presence of Nextera transposase I7 (in R1 reads) and I5 (in R2 reads) sequences in NextRAD data.
# By looking at catalog of Nextera sequences from bbmap (bbmap/resources/nextera.fa.gz), the sequences for these adaptors were determined.
# These were passed to Stacks, for trimming.
# We specify a barcode mismatch of 2, in order to account for both the Nextera I5 sequence and the NextRAD I5 sequence (I7 sequence unchanged)

# Old command, without trimming
process_radtags -p /RAID1/IMLS_GCCO/RawData/GC3F-PE-4637 --paired -b /RAID1/IMLS_GCCO/Analysis/Stacks/Barcodes.txt --index-index \
-o /RAID1/IMLS_GCCO/Analysis/Stacks/process_RADtags -c -q --disable_rad_check --len-limit 100

# New command, with trimming
process_radtags -p /RAID1/IMLS_GCCO/RawData/GC3F-PE-4637 --paired -b /RAID1/IMLS_GCCO/Analysis/Stacks/Barcodes.txt --index-index \
-o /RAID1/IMLS_GCCO/Analysis/Stacks/process_RADtags -c -q --adapter_1 CTGTCTCTTATACACATCTCCGAGCCCACGAGAC --adapter_2 CTGTCTCTTATACACATCTGACGCTGCCGACGA --adapter_mm 2 --disable_rad_check --len-limit 100

# When process_radtags completes, separate the remainder reads into a new directory
# These reads represent samples that have fallen out of phase from the paired end read, due to a quality control removal
mkdir RemainderReads
mv *.rem.?.fq.gz RemainderReads/

# The primary files generated in this step are used as the input for subsequent Stacks commands (denovo_map.pl or ref_map.pl)
