# Read in .csv, containing Q values for each of a specified number of populations
# Comes from ClumppIndFile.output file generated by CLUMPP program (part of CLUMPAK; file path K=7/CLUMPP.files/) 

# Lists individual IDs, population IDs, and Q values for each pop. Default command reads UTF-8
k7 <- read.table("K7_ClumppIndFile.output.tsv", header=T, fileEncoding="UTF-7")

# Make a vector of names
names <- k7$PopID
# Make a vector for name positions on graph
labelPos <- c(1,2,3.4,4.4,5.6,7,8,9.2,10.5,11.7,12.9,14)

# Plotting function for K of any value
plot_k <- function(klist,labelPositions,...){
  # List of colors, which are combinations of RGB components, in hexadecimal  
  colors <- c("#2171B5","#D95F02","#7570B3","#E7298A","#66A61E","#8C510A","#666666")
  # Graphing parameters
  for(i in 1:length(klist)){
    if(i==1){
      # Initial barplot
      barplot(klist[,i], horiz=F, beside=F, col=colors[i], axisnames=T, space=0.2, yaxt= "n", main="K=7")
      off.value <- klist[,i]
    }else{
      # Subsequent barplots with offset
      barplot(klist[,i], offset=off.value, add=T, beside=F, xlim=c(0,100), horiz=F, col=colors[i], yaxt= "n")
      off.value <- off.value + klist[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
  # Add group labels
  text(x=labelPositions, y=-0.031, srt=45, adj=1, xpd=TRUE, labels=names, cex=1)
}

plot_k(k7[,4:10], labelPos)
