# %%%%%%%%%%%%%%%%%%%%%%
# %%% PLOT STRUCTURE %%%
# %%%%%%%%%%%%%%%%%%%%%%

# This script declares a function for taking the the summarized Q matrix values 
# from a CLUMPP run and building a corresponding STRUCTURE plot.Specifically, 
# in terms of the outputs from CLUMPAK, for a given K value, it reads
# in the CLUMPP output file ("CLUMPP.files/ClumppIndFile,output") 
# and will plot those values.

# It then uses that function to plot the STRUCTURE outputs for QUAC and QUBO datasets,
# using garden and wild samples as well as wild samples only

library(RColorBrewer)

# %%%% FUNCTIONS %%%% ----
# Read in the file generated by CLUMPP, and add/remove columns as required 
read.CLUMPP <- function(clumpp.outputFile){
  # Read int the CLUMPP output file
  Qmat <- read.table(clumpp.outputFile, header=TRUE)
  # Remove the first 5 columns, which contain sample identifiers and other characters
  Qmat <- Qmat[,-(1:5)]
  return(Qmat)
}

# Plotting function for K of a single value
plot_singleK <- function(kList, kColors, ...){
  # Graphing parameters
  par(mar=c(7,2,10,1)+0.1, mgp = c(3,1,1))
  # Plotting 
  for(i in 1:length(kList)){
    if(i==1){
      # Initial barplot
      barplot(klist[,i], xlim=c(0,(nrow(klist)+20)), horiz=F, beside=F, col=kColors[i], 
              axisnames=T, space=0.2, yaxt= "n", main="")
      off.value <- kList[,i]
    }else{
      # Subsequent barplots with offset
      barplot(klist[,i], offset=off.value, add=T, beside=F, xlim=c(0,(nrow(kList)+20)), 
              horiz=F, col=kColors[i], yaxt= "n")
      off.value <- off.value + kList[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
}

# plot chains with species labels 
plot_multipleK <- function(nInds, kList, kValues, kColors, ...){
  # Define colors
  # cols <- c("#2171B5","#D95F02","#7570B3","#E7298A","#66A61E","#8C510A","#666666","#B3E2CD","#FDCDAC","#CBD5E8","#F4CAE4","#E6F5C9","#FFF2AE","#F1E2CC","#CCCCCC")
  # Set graphing parameters, in order to fit specified number of Ks
  par(mfrow = c(length(kList),1), mar = c(1.5,1,1.3,1) + 0.1, oma = c(5,0,1,0), mgp = c(2,1,0))
  # locations of each column
  # b <- as.data.frame(matrix(ncol = 1, nrow = nInds))
  # b[,1] <- barplot(t(kList[[1]][1]), beside= F, col= kColors, cex.name= 1, cex.axis= 1.2, border = 1, space = 0.05, xaxt = 'n', yaxt = 'n', cex.lab = 1, cex.main=1.6)
  # Plot 
  for(i in 1:length(kList)){
    # main plot call, and title call
    barplot(t(kList[[i]]), beside= F, col= kColors, border = 1, space = 0.05, xaxt = 'n', yaxt = 'n', cex.lab = 1.2)
    title(main = paste("K =", kValues[i], sep = ' '), line=0.2, cex.main=1.6)
    # y axis
    axis(2, at = c(0, 0.25, 0.5, 0.75, 1), cex.axis = 1, las = 2, pos = -0.02)
  }
}

# Function for plotting multiple
structure_plot <- function(nInds, klist, Ks, Kcolors){
  # define colors (16, for maximum number of Ks)
  # cols <- c("#2171B5","#D95F02","#7570B3","#E7298A","#66A61E","#8C510A","#666666","#B3E2CD","#FDCDAC","#CBD5E8","#F4CAE4","#E6F5C9","#FFF2AE","#F1E2CC","#CCCCCC")
  # locations of each column
  b <- as.data.frame(matrix(ncol = 1, nrow = nInds))
  b[,1] <- barplot(t(klist[[1]][1]), beside= F, col= Kcolors, cex.name= 1, cex.axis= 1.2, border = 1, space = 0.05, xaxt = 'n', yaxt = 'n', cex.lab = 1, cex.main=1.6)
  # plot
  plot_q_per_chain(klist, Ks)
}

# WORKING ----
# Variable file path: directory containing all CLUMPPs output to read in
clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/structure/denovo_finalAssemblies/QUAC/R80/garden_wild/firstSNP/output/CLUMPAK/QUAC_gardenAndWild_CLUMPAK/"

# Single K (QUAC garden and wild, K=6)
clummppFilepath <- paste0(clumppDir, "/K6/CLUMPP.files/ClumppIndFile.output")

test <- read.table(clummppFilepath, header=T)
test <- test[,-(1:5)]

testColors <- brewer.pal(6,"Dark2")
plot_singleK(test,Kcolors = testColors)

# Multiple Ks (QUAC garden and wild, K=2-7)
K2filepath <- paste0(clumppDir, "/K2/CLUMPP.files/ClumppIndFile.output")
K2clumpp <- read.CLUMPP(K2filepath)

K3filepath <- paste0(clumppDir, "/K3/CLUMPP.files/ClumppIndFile.output")
K3clumpp <- read.CLUMPP(K3filepath)

K4filepath <- paste0(clumppDir, "/K4/CLUMPP.files/ClumppIndFile.output")
K4clumpp <- read.CLUMPP(K4filepath)

K5filepath <- paste0(clumppDir, "/K5/CLUMPP.files/ClumppIndFile.output")
K5clumpp <- read.CLUMPP(K5filepath)

K6filepath <- paste0(clumppDir, "/K6/CLUMPP.files/ClumppIndFile.output")
K6clumpp <- read.CLUMPP(K6filepath)

K7filepath <- paste0(clumppDir, "/K7/CLUMPP.files/ClumppIndFile.output")
K7clumpp <- read.CLUMPP(K7filepath)

K2_4 <- list(K2clumpp, K3clumpp, K4clumpp)
K5_7 <- list(K5clumpp, K6clumpp, K7clumpp)
K2_7 <- list(K2clumpp, K3clumpp, K4clumpp, 
             K5clumpp, K6clumpp, K7clumpp)

structure_plot(nInds = 192, klist = K2_4, Ks=(2:4), Kcolors = testColors)
structure_plot(nInds = 192, klist = K5_7, Ks=(5:7), Kcolors = testColors)
structure_plot(nInds = 192, klist = K2_7, Ks=(2:7), Kcolors = testColors)

testColors <- c("#2171B5","#D95F02","#7570B3","#E7298A","#66A61E","#8C510A","#666666","#B3E2CD","#FDCDAC","#CBD5E8","#F4CAE4","#E6F5C9","#FFF2AE","#F1E2CC","#CCCCCC")
plot_multipleK(nInds = 192, kList = K2_4, kValues=(2:4), kColors=testColors)
plot_multipleK(nInds = 192, kList = K5_7, kValues=(5:7), kColors=testColors)
plot_multipleK(nInds = 192, kList = K2_7, kValues=(2:7), kColors=testColors)


# %%% READING IN DEMO FILE %%%----
# Reading in K7_subset file, an updated version of the CLUMPAK K7.output file. 
# Comes from JuneSubset ipyrad/STRUCTURE run
# This contains samples in their presented order, and has capillaris and one Troy Peak sample removed from file
k7 <- read.table("K7_plot.csv", header=T)

# Make a vector of names
names <- c("cusickiana_SRP","cusickiana_Jarbidge","cusickiana_Owyhee","maguirei","domensis","nevadensis_GRBA","nevadensis_Troy", "parryi")
# Make a vector for name positions on graph
labelPos <- c(16, 32, 37, 50, 71, 82, 88, 94)

# Plotting function for K of any value
plot_k <- function(klist,labelPositions,...){
  # List of colors, which are combinations of RGB components, in hexadecimal  
  colors <- c("#2171B5","#D95F02","#7570B3","#E7298A","#66A61E","#8C510A","#666666")
  # Graphing parameters
  par(mar=c(7,2,10,1)+0.1, mgp = c(3,1,1))
  for(i in 1:length(klist)){
    if(i==1){
      # Initial barplot
      barplot(klist[,i], xlim=c(0,100), horiz=F, beside=F, col=colors[i], axisnames=T, space=0.2, yaxt= "n", main="K=7")
      off.value <- klist[,i]
    }else{
      # Subsequent barplots with offset
      barplot(klist[,i], offset=off.value, add=T, beside=F, xlim=c(0,100), horiz=F, col=colors[i], yaxt= "n")
      off.value <- off.value + klist[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
  # Add group labels
  text(x=labelPositions, y=-0.031, srt=35, adj=1, xpd=TRUE, labels=names, cex=1.2)
}
dev.off()
plot_k(k7[,4:10], labelPos)
# Plotting lines beneath groups
lineWidth <- 1.9; lineHeight <- rep(-0.015,2)

lines(x = c(0.3,28.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(29.4,34.4), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(35.1,39.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(40.0,60.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(61.5,78.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(79.5,84.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(85.5,89.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(90.5,98.0), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)

# %%% PLOTTING DIFFERENT CLUSTERS FOR K=6 %%%----
# Code for plotting function
plot_k6 <- function(klist,main,...){
  cols <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF') # Combination of RGB components, in hexadecimal  
  #par(mfrow = c(length(klist),1), mar=c(0.1,0.1,0.1,0.1)+0.1, oma = c(15,0,0,0), mgp = c(1,1,0))
  for(i in 1:length(klist)){
    if(i==1){
      barplot(klist[,i], xlim=c(0,100), horiz=F, beside=F, col=cols[i], axisnames=T, space=0.2, yaxt= "n", main=main)
      off.value <- klist[,i]
    }else{
      barplot(klist[,i], offset=off.value, add=T, beside=F, xlim=c(0,100), horiz=F, col=cols[i], yaxt= "n")
      off.value <- off.value + klist[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), cex.axis = 1, las = 2, pos = -0.2)
}

# Major cluster
k6 <- read.table("ClumppIndFile.output", header=F)
# Remove useless columns
k6 <-k6[,-(1:5)]
plot_k6(k6, main="K=6 Major Cluster")

# Minor cluster 1
k6 <- read.table("ClumppIndFile.MinorCluster1", header=F)
# Remove useless columns
k6 <-k6[,-(1:5)]
plot_k6(k6, main="K=6 Minor Cluster 1")

# Minor cluster 2
k6 <- read.table("ClumppIndFile.MinorCluster2", header=F)
# Remove useless columns
k6 <-k6[,-(1:5)]
plot_k6(k6, main="K=6 Minor Cluster 2")

# %%% DEPRECATED CODE %%%----
# # Read in names file, containing sample IDs, groups, and coordinates (for later use)
# names <- c("Cusickiana_SRP","Cusickiana_Jarbidge","Cusickiana_Owyhee","Maguirei","Domensis","Nevadensis_GRBA","Nevadensis_Troy","Capillaris","Parryi")
# # Vector for name positions
# labelPos <- c(16, 32, 37, 50, 71, 82, 87, 91.5, 97)
# 
# plot_k6 <- function(klist,labelPositions,...){
#   #browser()
#   cols <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF') # Combination of RGB components, in hexadecimal  
#   #par(mfrow = c(length(klist),1), mar=c(0.1,0.1,0.1,0.1)+0.1, oma = c(15,0,0,0), mgp = c(1,1,0))
#   for(i in 1:length(klist)){
#     if(i==1){
#       barplot(klist[,i], xlim=c(0,100), horiz=F, beside=F, col=cols[i], axisnames=T, space=0.2, yaxt= "n")
#       off.value <- klist[,i]
#     }else{
#       barplot(klist[,i], offset=off.value, add=T, beside=F, xlim=c(0,100), horiz=F, col=cols[i], yaxt= "n")
#       off.value <- off.value + klist[,i]
#     }
#   }
#   # y axis
#   axis(2, at = c(0, 0.25, 0.5, 0.75, 1), cex.axis = 1, las = 2, pos = -0.2)
#   # Add group labels
#   #text(x=labelPositions, y=-0.025, srt=45, adj=1, xpd=TRUE, labels=names, cex=0.75)
# }
# plot.new()
# plot_k6(k6[,3:8], labelPos)
# 
# # Plotting lines beneath groups
# lineWidth <- 1.3; lineHeight <- rep(-0.015,2)
# 
# lines(x = c(0.2,28.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(29,34.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(35.2,39.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(40,61), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(61.5,79.1), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(79.6,83.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(84.3,89.8), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(90.3,92.3), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# lines(x = c(92.8,100.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)

# %%% K6 Stuff %%%

# # Plotting function for K=6
# plot_k6 <- function(klist,labelPositions,...){
#   # List of colors, which are combinations of RGB components, in hexadecimal  
#   cols <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF') 
#   # Graphing parameters
#   par(mar=c(5,2,4,1)+0.1, mgp = c(3,1,1))
#   for(i in 1:length(klist)){
#     if(i==1){
#       # Initial barplot
#       barplot(klist[,i], xlim=c(0,100), horiz=F, beside=F, col=cols[i], axisnames=T, space=0.2, yaxt= "n", main="K=6")
#       off.value <- klist[,i]
#     }else{
#       # Subsequent barplots with offset
#       barplot(klist[,i], offset=off.value, add=T, beside=F, xlim=c(0,100), horiz=F, col=cols[i], yaxt= "n")
#       off.value <- off.value + klist[,i]
#     }
#   }
#   # y axis
#   axis(2, at = c(0, 0.25, 0.5, 0.75, 1), labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
#   # Add group labels
#   text(x=labelPositions, y=-0.025, srt=45, adj=1, xpd=TRUE, labels=names, cex=0.8)
# }
# plot.new()
# plot_k6(k6[,3:8], labelPos)
# # Plotting lines beneath groups
# lineWidth <- 1.3; lineHeight <- rep(-0.015,2)

# Names with capillaris
# # Read in names file, containing sample IDs, groups, and coordinates (for later use)
# names <- c("cusickiana_Idaho","cusickiana_Jarbidge","cusickiana_Owyhee","maguirei","domensis","nevadensis_GRBA","nevadensis_Troy","capillaris","parryi")
# # Vector for name positions
# labelPos <- c(16, 32, 37, 50, 71, 82, 87, 91.5, 97)

# k6 <- read.table("K6.output", header=F)
# # Remove useless columns
# k6 <-k6[,-(2:5)]
# # Reorder columns based on demo file
# k6 <- k6[k2$Ind,]
# # Give sample names
# k6 <- cbind(k2$Group, k6)
# k6[,3:8]
