# %%%%%%%%%%%%%%%%%%%%%%
# %%% PLOT STRUCTURE %%%
# %%%%%%%%%%%%%%%%%%%%%%

# This script declares a function for taking the the summarized Q matrix values 
# from a CLUMPP run and building a corresponding STRUCTURE plot.Specifically, 
# in terms of the outputs from CLUMPAK, for a given K value, it reads
# in the CLUMPP output file ("CLUMPP.files/ClumppIndFile.output") 
# and will plot those values.

# It then uses that function to plot the STRUCTURE outputs for QUAC and QUBO datasets,
# using garden and wild samples as well as wild samples only

library(RColorBrewer)

# %%%% FUNCTIONS %%%% ----
# Read in the file generated by CLUMPP, and add/remove columns as required 
read.CLUMPP <- function(clumpp.outputFile){
  # Read int the CLUMPP output file
  Qmat <- read.table(clumpp.outputFile, header=FALSE)
  # Remove the first 5 columns, which contain sample identifiers and other characters
  Qmat <- Qmat[,-(1:5)]
  return(Qmat)
}

# Plotting function for single K value
plot_singleK <- function(kList, kColors, title, ...){
  # Plotting 
  for(i in 1:length(kList)){
    if(i==1){
      # Initial barplot
      barplot(kList[,i], xlim=c(0,(nrow(kList)+20)), ylim=c(0,1.3), horiz=F, beside=F, 
              col=kColors[i], axisnames=T, space=0.2, yaxt= "n", main=title)
      off.value <- kList[,i]
    }else{
      # Subsequent barplots with offset
      barplot(kList[,i], offset=off.value, add=T, beside=F, xlim=c(0,(nrow(kList)+20)), 
              horiz=F, col=kColors[i], yaxt= "n")
      off.value <- off.value + kList[,i]
    }
  }
  # y axis
  axis(2, at = c(0, 0.25, 0.5, 0.75, 1), labels=c("0", "0.25", "0.50", "0.75", "1.00"), cex.axis = 1, las = 2, pos = -0.2, xpd=T)
}

# Plotting function for multiple K values
plot_multipleK <- function(kList, kValues, kColors, ...){
  # Determine the number of individuals by counting rows of the kList object
  nInds <- nrow(kList[[1]])
  # Set graphing parameters to allow for multiple rows (for each K value)
  par(mfrow = c(length(kList),1), mar = c(2,1,2,0.75) + 0.1, oma = c(1,0,3,0), mgp = c(2,1,0))
  # Loop through list of Q matrices
  for(i in 1:length(kList)){
    # Main plot call, and title call
    barplot(t(kList[[i]]), beside= F, col=kColors, border = 1, space = 0.05, 
            xaxt = 'n', yaxt = 'n', cex.lab = 1.2)
    title(main = paste("K =", kValues[i], sep = ' '), line=0.2, cex.main=1.6)
    # y axis
    axis(2, at = c(0, 0.25, 0.5, 0.75, 1), cex.axis = 1, las = 2, pos = -0.02)
  }
}

# %%%% QUAC %%%% ----
# Colors for different clusters: combinations of RGB components in hexadecimal
QUAC.colors <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', 
                 '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF') 
# %%%% GARDEN & WILD ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/structure/denovo_finalAssemblies/QUAC/R80/garden_wild/firstSNP/output/CLUMPAK/QUAC_gardenAndWild_CLUMPAK_1659990425/"

# Read in Q matrices
K2filepath <- paste0(QUAC.clumppDir, "/K2/CLUMPP.files/ClumppIndFile.output")
K2clumpp <- read.CLUMPP(K2filepath)

K3filepath <- paste0(QUAC.clumppDir, "/K3/CLUMPP.files/ClumppIndFile.output")
K3clumpp <- read.CLUMPP(K3filepath)

K4filepath <- paste0(QUAC.clumppDir, "/K4/CLUMPP.files/ClumppIndFile.output")
K4clumpp <- read.CLUMPP(K4filepath)

K5filepath <- paste0(QUAC.clumppDir, "/K5/CLUMPP.files/ClumppIndFile.output")
K5clumpp <- read.CLUMPP(K5filepath)

K6filepath <- paste0(QUAC.clumppDir, "/K6/CLUMPP.files/ClumppIndFile.output")
K6clumpp <- read.CLUMPP(K6filepath)

K7filepath <- paste0(QUAC.clumppDir, "/K7/CLUMPP.files/ClumppIndFile.output")
K7clumpp <- read.CLUMPP(K7filepath)

# All Ks (QUAC garden and wild, K=2-7) ----
# QUAC.K2_4 <- list(K2clumpp, K3clumpp, K4clumpp)
# QUAC.K5_7 <- list(K5clumpp, K6clumpp, K7clumpp)
QUAC.K2_7 <- list(K2clumpp, K3clumpp, K4clumpp, 
             K5clumpp, K6clumpp, K7clumpp)
# plot_multipleK(kList = QUAC.K2_4, kValues=(2:4), kColors = QUAC.colors)
# plot_multipleK(kList = QUAC.K5_7, kValues=(5:7), kColors = QUAC.colors)
plot_multipleK(kList = QUAC.K2_7, kValues=(2:7), kColors = QUAC.colors)

# Designate groups beneath K charts. 1-96 are garden; 97-193 are wild
lineWidth <- 1.9; lineHeight <- rep(-0.2,2)
labelPositions <- c(48, 144); labelNames <- c("garden", "wild")

# Plot lines
lines(x = c(0.2,100.7), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(101.2,202.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=labelPositions, y=-0.3, srt=35, adj=1, xpd=TRUE, labels=labelNames, cex=1.2)
# Title
mtext(text = "QUAC, Garden and Wild", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(3,3,1,3), oma=c(1,0,1,0))
# Variables for lines beneath K charts. 1-96 are garden; 97-193 are wild
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
labelPositions <- c(48, 167); labelNames <- c("garden", "wild")
# Plot QUAC K=3 values (Evanno Best K)
plot_singleK(K3clumpp, kColors = QUAC.colors, title = "QUAC, Garden and Wild: K3 (Evanno)")
# Plot lines
lines(x = c(0.3,114.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(116,232), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=labelNames, cex=1.2)

# Plot QUAC K=6 values (Max Probability Best K)
plot_singleK(K6clumpp, kColors = QUAC.colors, title = "QUAC, Garden and Wild: K6 (Max Probability)")
# Plot lines
lines(x = c(0.3,114.5), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(116,232), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=labelPositions, y=-0.05, srt=35, adj=1, xpd=TRUE, labels=labelNames, cex=1.2)

# %%%% WILD ----
# Variable file path: directory containing all CLUMPPs output to read in
QUAC.W.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/structure/denovo_finalAssemblies/QUAC/R80/wild/firstSNP/output/CLUMPAK/QUAC_wild_CLUMPAK_1658778010/"

# Read in Q matrices
K2filepath <- paste0(QUAC.W.clumppDir, "/K2/CLUMPP.files/ClumppIndFile.output")
K2clumpp <- read.CLUMPP(K2filepath)

K3filepath <- paste0(QUAC.W.clumppDir, "/K3/CLUMPP.files/ClumppIndFile.output")
K3clumpp <- read.CLUMPP(K3filepath)

K4filepath <- paste0(QUAC.W.clumppDir, "/K4/CLUMPP.files/ClumppIndFile.output")
K4clumpp <- read.CLUMPP(K4filepath)

K5filepath <- paste0(QUAC.W.clumppDir, "/K5/CLUMPP.files/ClumppIndFile.output")
K5clumpp <- read.CLUMPP(K5filepath)

K6filepath <- paste0(QUAC.W.clumppDir, "/K6/CLUMPP.files/ClumppIndFile.output")
K6clumpp <- read.CLUMPP(K6filepath)

K7filepath <- paste0(QUAC.W.clumppDir, "/K7/CLUMPP.files/ClumppIndFile.output")
K7clumpp <- read.CLUMPP(K7filepath)

# All Ks (QUAC wild, K=2-7) ----
# QUAC.W.K2_4 <- list(K2clumpp, K3clumpp, K4clumpp)
# QUAC.W.K5_7 <- list(K5clumpp, K6clumpp, K7clumpp)
QUAC.W.K2_7 <- list(K2clumpp, K3clumpp, K4clumpp, 
                  K5clumpp, K6clumpp, K7clumpp)
# plot_multipleK(kList = QUAC.W.K2_4, kValues=(2:4), kColors = QUAC.colors)
# plot_multipleK(kList = QUAC.W.K5_7, kValues=(5:7), kColors = QUAC.colors)
plot_multipleK(kList = QUAC.W.K2_7, kValues=(2:7), kColors = QUAC.colors)
# Title
mtext(text = "QUAC, Wild", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(3,3,1,3), oma=c(1,0,1,0))
# Plot QUAC K=3 values (Evanno Best K)
plot_singleK(K3clumpp, kColors = QUAC.colors, title = "QUAC, Wild: K3 (Evanno)")
# Plot QUAC K=4 values (Max Probability Best K)
plot_singleK(K4clumpp, kColors = QUAC.colors, title = "QUAC, Wild: K4 (Max Probability)")

# %%%% QUBO %%%% ----
# Colors for different clusters: combinations of RGB components in hexadecimal
QUBO.colors <- c('#A8FFFD','#B862D3', '#A39D9D','#FFFF00', 
                 '#69C261', '#FF59AC', '#26CDCD',  '#C1C6FF')
# %%%% GARDEN & WILD ----
# Variable file path: directory containing all CLUMPPs output to read in
QUBO.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/structure/reference_filteredReads/QUBO/R80/garden_wild/firstSNP/output/CLUMPAK/QUBO_gardenAndWild_CLUMPAK_1658769113/"

# Read in Q matrices
K2filepath <- paste0(QUBO.clumppDir, "/K2/CLUMPP.files/ClumppIndFile.output")
K2clumpp <- read.CLUMPP(K2filepath)

K3filepath <- paste0(QUBO.clumppDir, "/K3/CLUMPP.files/ClumppIndFile.output")
K3clumpp <- read.CLUMPP(K3filepath)

K4filepath <- paste0(QUBO.clumppDir, "/K4/CLUMPP.files/ClumppIndFile.output")
K4clumpp <- read.CLUMPP(K4filepath)

K5filepath <- paste0(QUBO.clumppDir, "/K5/CLUMPP.files/ClumppIndFile.output")
K5clumpp <- read.CLUMPP(K5filepath)

K6filepath <- paste0(QUBO.clumppDir, "/K6/CLUMPP.files/ClumppIndFile.output")
K6clumpp <- read.CLUMPP(K6filepath)

K7filepath <- paste0(QUBO.clumppDir, "/K7/CLUMPP.files/ClumppIndFile.output")
K7clumpp <- read.CLUMPP(K7filepath)

K8filepath <- paste0(QUBO.clumppDir, "/K8/CLUMPP.files/ClumppIndFile.output")
K8clumpp <- read.CLUMPP(K8filepath)

# All Ks (QUBO garden and wild, K=2-8) ----
# QUBO.K2_4 <- list(K2clumpp, K3clumpp, K4clumpp)
# QUBO.K5_8 <- list(K5clumpp, K6clumpp, K7clumpp, K8clumpp)
QUBO.K2_8 <- list(K2clumpp, K3clumpp, K4clumpp, 
             K5clumpp, K6clumpp, K7clumpp, K8clumpp)
# plot_multipleK(kList = QUBO.K2_4, kValues=(2:4), kColors = QUBO.colors)
# plot_multipleK(kList = QUBO.K5_8, kValues=(5:8), kColors = QUBO.colors)
plot_multipleK(kList = QUBO.K2_8, kValues=(2:8), kColors = QUBO.colors)

# Designate groups beneath K charts. 1-85 are garden; 86-180 are wild
lineWidth <- 1.9; lineHeight <- rep(-0.2,2)
labelPositions <- c(42.5, 133); labelNames <- c("garden", "wild")

# Plot lines
lines(x = c(0.2,89), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(90.2,189), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=labelPositions, y=-0.3, srt=35, adj=1, xpd=TRUE, labels=labelNames, cex=1.2)
# Title
mtext(text = "QUBO, Garden and Wild", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(4,1.5,4,2), oma=c(2,0,2,1))
# Designate groups beneath K charts. 1-85 are garden; 86-180 are wild
lineWidth <- 1.9; lineHeight <- rep(-0.035,2)
labelPositions <- c(42.5, 133); labelNames <- c("garden", "wild")
# Plot QUAC K=5 values (Evanno Best K)
plot_singleK(K5clumpp, kColors = QUBO.colors, title = "QUBO, Garden and Wild: K5 (Evanno)")
# Plot lines
lines(x = c(0.2,89), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(90.2,213), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=labelPositions, y=-0.1, srt=35, adj=1, xpd=TRUE, labels=labelNames, cex=1.2)

# Plot QUAC K=6 values (Max Probability Best K)
plot_singleK(K6clumpp, kColors = QUBO.colors, title = "QUBO, Garden and Wild: K6 (Max Probability)")
# Plot lines
lines(x = c(0.2,89), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
lines(x = c(90.2,213), y = lineHeight, lwd = lineWidth, col = "black", xpd = NA)
# Add group labels
text(x=labelPositions, y=-0.1, srt=35, adj=1, xpd=TRUE, labels=labelNames, cex=1.2)

# %%%% WILD ----
# Variable file path: directory containing all CLUMPPs output to read in
QUBO.W.clumppDir <- 
  "/RAID1/IMLS_GCCO/Analysis/structure/reference_filteredReads/QUBO/R80/wild/output/CLUMPAK/QUBO_wild_CLUMPAK_1658771421/"

# Read in Q matrices
K2filepath <- paste0(QUBO.W.clumppDir, "/K2/CLUMPP.files/ClumppIndFile.output")
K2clumpp <- read.CLUMPP(K2filepath)

K3filepath <- paste0(QUBO.W.clumppDir, "/K3/CLUMPP.files/ClumppIndFile.output")
K3clumpp <- read.CLUMPP(K3filepath)

K4filepath <- paste0(QUBO.W.clumppDir, "/K4/CLUMPP.files/ClumppIndFile.output")
K4clumpp <- read.CLUMPP(K4filepath)

K5filepath <- paste0(QUBO.W.clumppDir, "/K5/CLUMPP.files/ClumppIndFile.output")
K5clumpp <- read.CLUMPP(K5filepath)

K6filepath <- paste0(QUBO.W.clumppDir, "/K6/CLUMPP.files/ClumppIndFile.output")
K6clumpp <- read.CLUMPP(K6filepath)

K7filepath <- paste0(QUBO.W.clumppDir, "/K7/CLUMPP.files/ClumppIndFile.output")
K7clumpp <- read.CLUMPP(K7filepath)

K8filepath <- paste0(QUBO.W.clumppDir, "/K8/CLUMPP.files/ClumppIndFile.output")
K8clumpp <- read.CLUMPP(K8filepath)

# All Ks (QUBO wild, K=2-8) ----
# QUBO.W.K2_4 <- list(K2clumpp, K3clumpp, K4clumpp)
# QUBO.W.K5_8 <- list(K5clumpp, K6clumpp, K7clumpp, K8clumpp)
QUBO.W.K2_8 <- list(K2clumpp, K3clumpp, K4clumpp, 
                    K5clumpp, K6clumpp, K7clumpp, K8clumpp)
# plot_multipleK(kList = QUBO.W.K2_4, kValues=(2:4), kColors = QUBO.colors)
# plot_multipleK(kList = QUBO.W.K5_8, kValues=(5:8), kColors = QUBO.colors)
plot_multipleK(kList = QUBO.W.K2_8, kValues=(2:8), kColors = QUBO.colors)
# Title
mtext(text = "QUBO, Wild", outer=TRUE, cex=1.3)

# Best K ----
# Plot two charts per window (one for each Best K metric)
par(mfrow=c(2,1), mar = c(3,3,1,3), oma=c(1,0,1,0))
# Plot QUBO K=3 values (Evanno and Max Probability Best K)
plot_singleK(K3clumpp, kColors = QUAC.colors, title = "QUBO, Wild: K3 (Evanno, Max Probability)")
